import type { Tool, Review, LeaderboardEntry } from './types';

export const MOCK_TOOLS: Tool[] = [
  {
    id: '1', slug: 'writesonic', name: 'Writesonic', tagline: 'AI writing assistant for teams',
    description: 'Writesonic is an AI-powered writing platform that helps you create SEO-optimized content, ads, emails, and more in seconds.',
    logo_url: 'https://logo.clearbit.com/writesonic.com',
    website_url: 'https://writesonic.com', category: 'AI Writing', pricing_model: 'Freemium',
    tags: ['writing', 'SEO', 'content', 'AI'], badges: ['top_rated', 'featured'],
    upvote_count: 1284, review_count: 342, average_rating: 4.7, rank_score: 9820,
    is_featured: true, is_verified: true, is_pro: true,
    promotional_banner: 'Get 3 months free with code LAUNCH2026',
    promotional_cta: 'Claim Offer', launched_at: '2024-01-15', created_at: '2024-01-15', updated_at: '2026-03-01',
  },
  {
    id: '2', slug: 'notion-ai', name: 'Notion AI', tagline: 'Your AI-powered workspace',
    description: 'Notion AI brings the power of AI directly into your Notion workspace, helping you write, summarize, brainstorm, and more.',
    logo_url: 'https://logo.clearbit.com/notion.so',
    website_url: 'https://notion.so', category: 'AI Productivity', pricing_model: 'Freemium',
    tags: ['productivity', 'notes', 'AI', 'workspace'], badges: ['editors_pick'],
    upvote_count: 2156, review_count: 891, average_rating: 4.8, rank_score: 9650,
    is_featured: true, is_verified: true, is_pro: false,
    launched_at: '2023-11-01', created_at: '2023-11-01', updated_at: '2026-02-28',
  },
  {
    id: '3', slug: 'midjourney', name: 'Midjourney', tagline: 'AI image generation for creatives',
    description: 'Midjourney is an independent research lab exploring new mediums of thought and expanding the imaginative powers of the human species.',
    logo_url: 'https://logo.clearbit.com/midjourney.com',
    website_url: 'https://midjourney.com', category: 'AI Image', pricing_model: 'Paid',
    tags: ['image', 'art', 'creative', 'AI'], badges: ['top_rated', 'community_pick'],
    upvote_count: 3421, review_count: 1204, average_rating: 4.9, rank_score: 9580,
    is_featured: false, is_verified: true, is_pro: false,
    launched_at: '2022-07-12', created_at: '2022-07-12', updated_at: '2026-03-05',
  },
  {
    id: '4', slug: 'linear', name: 'Linear', tagline: 'The issue tracker for modern teams',
    description: 'Linear is the new standard for modern software development. Streamline issues, sprints, and product roadmaps.',
    logo_url: 'https://logo.clearbit.com/linear.app',
    website_url: 'https://linear.app', category: 'Project Management', pricing_model: 'Freemium',
    tags: ['project management', 'issues', 'sprints', 'roadmap'], badges: ['laudstack_pick'],
    upvote_count: 1876, review_count: 654, average_rating: 4.8, rank_score: 9420,
    is_featured: false, is_verified: true, is_pro: true,
    launched_at: '2020-01-01', created_at: '2020-01-01', updated_at: '2026-03-01',
  },
  {
    id: '5', slug: 'cursor-ai', name: 'Cursor', tagline: 'The AI-first code editor',
    description: 'Cursor is the AI-first code editor. Build software faster in an editor designed for pair-programming with AI.',
    logo_url: 'https://logo.clearbit.com/cursor.com',
    website_url: 'https://cursor.sh', category: 'AI Code', pricing_model: 'Freemium',
    tags: ['coding', 'AI', 'editor', 'developer'], badges: ['trending', 'new_launch'],
    upvote_count: 2890, review_count: 743, average_rating: 4.7, rank_score: 9380,
    is_featured: true, is_verified: true, is_pro: false,
    launched_at: '2023-03-14', created_at: '2023-03-14', updated_at: '2026-03-07',
  },
  {
    id: '6', slug: 'descript', name: 'Descript', tagline: 'Edit video like a doc',
    description: 'Descript is the only tool you need to write, record, transcribe, edit, collaborate, and share your videos and podcasts.',
    logo_url: 'https://logo.clearbit.com/descript.com',
    website_url: 'https://descript.com', category: 'AI Video', pricing_model: 'Freemium',
    tags: ['video', 'podcast', 'editing', 'transcription'], badges: ['verified'],
    upvote_count: 987, review_count: 312, average_rating: 4.5, rank_score: 8920,
    is_featured: false, is_verified: true, is_pro: false,
    launched_at: '2019-06-01', created_at: '2019-06-01', updated_at: '2026-02-20',
  },
  {
    id: '7', slug: 'perplexity', name: 'Perplexity AI', tagline: 'AI-powered search engine',
    description: 'Perplexity AI is a conversational search engine that uses AI to provide direct answers to questions with cited sources.',
    logo_url: 'https://logo.clearbit.com/perplexity.ai',
    website_url: 'https://perplexity.ai', category: 'AI Analytics', pricing_model: 'Freemium',
    tags: ['search', 'research', 'AI', 'answers'], badges: ['best_value'],
    upvote_count: 1543, review_count: 421, average_rating: 4.6, rank_score: 8750,
    is_featured: false, is_verified: true, is_pro: false,
    launched_at: '2022-12-07', created_at: '2022-12-07', updated_at: '2026-03-04',
  },
  {
    id: '8', slug: 'loom', name: 'Loom', tagline: 'Async video messaging for work',
    description: 'Loom is a video messaging tool that helps you get your message across through instantly shareable videos.',
    logo_url: 'https://logo.clearbit.com/loom.com',
    website_url: 'https://loom.com', category: 'AI Video', pricing_model: 'Freemium',
    tags: ['video', 'async', 'communication', 'screen recording'], badges: [],
    upvote_count: 876, review_count: 289, average_rating: 4.4, rank_score: 8320,
    is_featured: false, is_verified: true, is_pro: false,
    launched_at: '2016-01-01', created_at: '2016-01-01', updated_at: '2026-02-15',
  },
];

export const MOCK_LEADERBOARD: LeaderboardEntry[] = MOCK_TOOLS.map((tool, i) => ({
  rank: i + 1,
  tool,
  rank_change: [2, -1, 0, 3, 1, -2, 0, -1][i] ?? 0,
  period: 'weekly',
}));

export const MOCK_REVIEWS: Review[] = [
  {
    id: 'r1', tool_id: '1', user_id: 'u1', rating: 5,
    title: 'Best AI writing tool I\'ve used',
    body: 'Writesonic has completely transformed how I create content. The quality is exceptional and it saves me hours every week.',
    pros: 'Fast, high quality output, great SEO features',
    cons: 'Can be a bit pricey for solo creators',
    use_case: 'Blog content and social media copy',
    is_verified_purchase: true, helpful_count: 42,
    created_at: '2026-02-15',
    user: { id: 'u1', name: 'Sarah Chen', avatar_url: undefined, role: 'Content Marketer', company: 'GrowthLabs' },
  },
  {
    id: 'r2', tool_id: '1', user_id: 'u2', rating: 4,
    title: 'Solid tool with room to grow',
    body: 'Overall very happy with Writesonic. The AI output is consistently good and the team ships updates regularly.',
    pros: 'Reliable, good templates, responsive support',
    cons: 'UI could be more intuitive',
    is_verified_purchase: true, helpful_count: 18,
    created_at: '2026-01-28',
    user: { id: 'u2', name: 'Marcus Rivera', role: 'Founder', company: 'Startup Studio' },
    founder_reply: {
      body: 'Thanks Marcus! We\'re actively working on a UI refresh — stay tuned for updates in Q2.',
      created_at: '2026-01-30',
    },
  },
];

export const CATEGORIES = [
  { name: 'All', icon: '✦', count: 95 },
  { name: 'AI Writing', icon: '✍️', count: 18 },
  { name: 'AI Image', icon: '🎨', count: 12 },
  { name: 'AI Code', icon: '💻', count: 14 },
  { name: 'AI Video', icon: '🎬', count: 8 },
  { name: 'AI Productivity', icon: '⚡', count: 16 },
  { name: 'Marketing', icon: '📣', count: 11 },
  { name: 'Developer Tools', icon: '🛠️', count: 9 },
  { name: 'Design', icon: '🎭', count: 7 },
];
