import type { Tool, Review, LeaderboardEntry } from './types';

export const MOCK_TOOLS: Tool[] = [
  {
    id: '1', slug: 'writesonic', name: 'Writesonic', tagline: 'AI writing assistant for teams',
    description: 'Writesonic is an AI-powered writing platform that helps you create SEO-optimized content, ads, emails, and more in seconds.',
    logo_url: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663413324407/3XGasP8CcX57JRU5Ai2Hv7/final_writesonic_6c26b8c5.png',
    website_url: 'https://writesonic.com', category: 'AI Writing', pricing_model: 'Freemium',
    tags: ['writing', 'SEO', 'content', 'AI'], badges: ['top_rated', 'featured'],
    upvote_count: 1284, review_count: 342, average_rating: 4.7, rank_score: 9820,
    is_featured: true, is_verified: true, is_pro: true,
    promotional_banner: 'Get 3 months free with code LAUNCH2026',
    promotional_cta: 'Claim Offer', launched_at: '2024-01-15', created_at: '2024-01-15', updated_at: '2026-03-01',
  },
  {
    id: '2', slug: 'notion-ai', name: 'Notion AI', tagline: 'Your AI-powered workspace',
    description: 'Notion AI brings the power of AI directly into your Notion workspace, helping you write, summarize, brainstorm, and more.',
    logo_url: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663413324407/3XGasP8CcX57JRU5Ai2Hv7/final_notion_0a99acbe.png',
    website_url: 'https://notion.so', category: 'AI Productivity', pricing_model: 'Freemium',
    tags: ['productivity', 'notes', 'AI', 'workspace'], badges: ['editors_pick'],
    upvote_count: 2156, review_count: 891, average_rating: 4.8, rank_score: 9650,
    is_featured: true, is_verified: true, is_pro: false,
    launched_at: '2023-11-01', created_at: '2023-11-01', updated_at: '2026-02-28',
  },
  {
    id: '3', slug: 'midjourney', name: 'Midjourney', tagline: 'AI image generation for creatives',
    description: 'Midjourney is an independent research lab exploring new mediums of thought and expanding the imaginative powers of the human species.',
    logo_url: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663413324407/3XGasP8CcX57JRU5Ai2Hv7/final_midjourney_63ab8156.png',
    website_url: 'https://midjourney.com', category: 'AI Image', pricing_model: 'Paid',
    tags: ['image', 'art', 'creative', 'AI'], badges: ['top_rated', 'community_pick'],
    upvote_count: 3421, review_count: 1204, average_rating: 4.9, rank_score: 9580,
    is_featured: false, is_verified: true, is_pro: false,
    launched_at: '2022-07-12', created_at: '2022-07-12', updated_at: '2026-03-05',
  },
  {
    id: '4', slug: 'linear', name: 'Linear', tagline: 'The issue tracker for modern teams',
    description: 'Linear is the new standard for modern software development. Streamline issues, sprints, and product roadmaps.',
    logo_url: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663413324407/3XGasP8CcX57JRU5Ai2Hv7/final_linear_955e86a4.png',
    website_url: 'https://linear.app', category: 'Project Management', pricing_model: 'Freemium',
    tags: ['project management', 'issues', 'sprints', 'roadmap'], badges: ['laudstack_pick'],
    upvote_count: 1876, review_count: 654, average_rating: 4.8, rank_score: 9420,
    is_featured: false, is_verified: true, is_pro: true,
    launched_at: '2020-01-01', created_at: '2020-01-01', updated_at: '2026-03-01',
  },
  {
    id: '5', slug: 'cursor-ai', name: 'Cursor', tagline: 'The AI-first code editor',
    description: 'Cursor is the AI-first code editor. Build software faster in an editor designed for pair-programming with AI.',
    logo_url: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663413324407/3XGasP8CcX57JRU5Ai2Hv7/final_cursor_84dc4659.png',
    website_url: 'https://cursor.sh', category: 'AI Code', pricing_model: 'Freemium',
    tags: ['coding', 'AI', 'editor', 'developer'], badges: ['trending', 'new_launch'],
    upvote_count: 2890, review_count: 743, average_rating: 4.7, rank_score: 9380,
    is_featured: true, is_verified: true, is_pro: false,
    launched_at: '2023-03-14', created_at: '2023-03-14', updated_at: '2026-03-07',
  },
  {
    id: '6', slug: 'descript', name: 'Descript', tagline: 'Edit video like a doc',
    description: 'Descript is the only tool you need to write, record, transcribe, edit, collaborate, and share your videos and podcasts.',
    logo_url: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663413324407/3XGasP8CcX57JRU5Ai2Hv7/final_descript_b875598c.png',
    website_url: 'https://descript.com', category: 'AI Video', pricing_model: 'Freemium',
    tags: ['video', 'podcast', 'editing', 'transcription'], badges: ['verified'],
    upvote_count: 987, review_count: 312, average_rating: 4.5, rank_score: 8920,
    is_featured: false, is_verified: true, is_pro: false,
    launched_at: '2019-06-01', created_at: '2019-06-01', updated_at: '2026-02-20',
  },
  {
    id: '7', slug: 'perplexity', name: 'Perplexity AI', tagline: 'AI-powered search engine',
    description: 'Perplexity AI is a conversational search engine that uses AI to provide direct answers to questions with cited sources.',
    logo_url: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663413324407/3XGasP8CcX57JRU5Ai2Hv7/final_perplexity_93d4d01c.png',
    website_url: 'https://perplexity.ai', category: 'AI Analytics', pricing_model: 'Freemium',
    tags: ['search', 'research', 'AI', 'answers'], badges: ['best_value'],
    upvote_count: 1543, review_count: 421, average_rating: 4.6, rank_score: 8750,
    is_featured: false, is_verified: true, is_pro: false,
    launched_at: '2022-12-07', created_at: '2022-12-07', updated_at: '2026-03-04',
  },
  {
    id: '8', slug: 'loom', name: 'Loom', tagline: 'Async video messaging for work',
    description: 'Loom is a video messaging tool that helps you get your message across through instantly shareable videos.',
    logo_url: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663413324407/3XGasP8CcX57JRU5Ai2Hv7/final_loom_7f5999c2.png',
    website_url: 'https://loom.com', category: 'AI Video', pricing_model: 'Freemium',
    tags: ['video', 'async', 'communication', 'screen recording'], badges: [],
    upvote_count: 876, review_count: 289, average_rating: 4.4, rank_score: 8320,
    is_featured: false, is_verified: true, is_pro: false,
    launched_at: '2016-01-01', created_at: '2016-01-01', updated_at: '2026-02-15',
  },
  {
    id: '9', slug: 'github-copilot', name: 'GitHub Copilot', tagline: 'Your AI pair programmer',
    description: 'GitHub Copilot uses AI to suggest code and entire functions in real-time, right from your editor. Trained on billions of lines of public code.',
    logo_url: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663413324407/3XGasP8CcX57JRU5Ai2Hv7/final_github_copilot_d937f99a.png',
    website_url: 'https://github.com/features/copilot', category: 'AI Code', pricing_model: 'Paid',
    tags: ['coding', 'AI', 'autocomplete', 'developer'], badges: ['top_rated', 'editors_pick'],
    upvote_count: 4210, review_count: 1532, average_rating: 4.8, rank_score: 9900,
    is_featured: true, is_verified: true, is_pro: true,
    launched_at: '2021-06-29', created_at: '2021-06-29', updated_at: '2026-03-01',
  },
  {
    id: '10', slug: 'figma', name: 'Figma', tagline: 'Collaborative interface design tool',
    description: 'Figma is a cloud-based design tool that enables teams to create, prototype, and collaborate on UI/UX designs in real time.',
    logo_url: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663413324407/3XGasP8CcX57JRU5Ai2Hv7/final_figma_dd873bf8.png',
    website_url: 'https://figma.com', category: 'Design', pricing_model: 'Freemium',
    tags: ['design', 'UI/UX', 'prototyping', 'collaboration'], badges: ['top_rated', 'community_pick'],
    upvote_count: 5120, review_count: 2341, average_rating: 4.9, rank_score: 9850,
    is_featured: true, is_verified: true, is_pro: false,
    launched_at: '2016-09-27', created_at: '2016-09-27', updated_at: '2026-03-01',
  },
  {
    id: '11', slug: 'vercel', name: 'Vercel', tagline: 'Deploy web apps instantly',
    description: 'Vercel is a cloud platform for frontend developers, providing the speed and reliability innovators need to create at the moment of inspiration.',
    logo_url: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663413324407/3XGasP8CcX57JRU5Ai2Hv7/final_vercel_5405f962.png',
    website_url: 'https://vercel.com', category: 'Developer Tools', pricing_model: 'Freemium',
    tags: ['deployment', 'hosting', 'frontend', 'CI/CD'], badges: ['laudstack_pick', 'trending'],
    upvote_count: 3890, review_count: 1120, average_rating: 4.8, rank_score: 9700,
    is_featured: false, is_verified: true, is_pro: false,
    launched_at: '2015-12-01', created_at: '2015-12-01', updated_at: '2026-03-01',
  },
  {
    id: '12', slug: 'supabase', name: 'Supabase', tagline: 'The open source Firebase alternative',
    description: 'Supabase is an open source backend-as-a-service. Start your project with a Postgres database, authentication, instant APIs, edge functions, and storage.',
    logo_url: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663413324407/3XGasP8CcX57JRU5Ai2Hv7/final_supabase_a87167a6.png',
    website_url: 'https://supabase.com', category: 'Developer Tools', pricing_model: 'Freemium',
    tags: ['database', 'backend', 'open source', 'PostgreSQL'], badges: ['trending', 'new_launch'],
    upvote_count: 3240, review_count: 876, average_rating: 4.7, rank_score: 9450,
    is_featured: false, is_verified: true, is_pro: false,
    launched_at: '2020-01-01', created_at: '2020-01-01', updated_at: '2026-03-01',
  },
  {
    id: '13', slug: 'framer', name: 'Framer', tagline: 'Design and publish stunning sites',
    description: 'Framer is the professional website builder for creative teams. Design, prototype, and publish production-ready websites without writing code.',
    logo_url: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663413324407/3XGasP8CcX57JRU5Ai2Hv7/final_framer_cf53a1cf.png',
    website_url: 'https://framer.com', category: 'Design', pricing_model: 'Freemium',
    tags: ['design', 'no-code', 'website builder', 'prototyping'], badges: ['editors_pick'],
    upvote_count: 2180, review_count: 654, average_rating: 4.6, rank_score: 9100,
    is_featured: false, is_verified: true, is_pro: false,
    launched_at: '2014-01-01', created_at: '2014-01-01', updated_at: '2026-03-01',
  },
  {
    id: '14', slug: 'claude', name: 'Claude', tagline: 'AI assistant by Anthropic',
    description: 'Claude is a next-generation AI assistant built by Anthropic. It is trained to be safe, accurate, and helpful for complex reasoning, analysis, and writing tasks.',
    logo_url: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663413324407/3XGasP8CcX57JRU5Ai2Hv7/final_claude_2d37b9be.png',
    website_url: 'https://claude.ai', category: 'AI Productivity', pricing_model: 'Freemium',
    tags: ['AI', 'assistant', 'writing', 'reasoning'], badges: ['top_rated', 'featured'],
    upvote_count: 3760, review_count: 1089, average_rating: 4.8, rank_score: 9600,
    is_featured: true, is_verified: true, is_pro: false,
    launched_at: '2023-03-14', created_at: '2023-03-14', updated_at: '2026-03-01',
  },
  {
    id: '15', slug: 'grammarly', name: 'Grammarly', tagline: 'AI writing and grammar assistant',
    description: 'Grammarly is an AI-powered writing assistant that helps you write clearly and effectively. It checks grammar, spelling, style, and tone across all your apps.',
    logo_url: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663413324407/3XGasP8CcX57JRU5Ai2Hv7/final_grammarly_e1861d88.png',
    website_url: 'https://grammarly.com', category: 'AI Writing', pricing_model: 'Freemium',
    tags: ['writing', 'grammar', 'AI', 'productivity'], badges: ['best_value'],
    upvote_count: 2890, review_count: 1432, average_rating: 4.5, rank_score: 8900,
    is_featured: false, is_verified: true, is_pro: false,
    launched_at: '2009-07-01', created_at: '2009-07-01', updated_at: '2026-03-01',
  },
  {
    id: '16', slug: 'canva', name: 'Canva', tagline: 'Design anything, anywhere',
    description: 'Canva is an online design and visual communication platform with a mission to empower everyone in the world to design anything and publish anywhere.',
    logo_url: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663413324407/3XGasP8CcX57JRU5Ai2Hv7/final_canva_9ffb3b85.png',
    website_url: 'https://canva.com', category: 'Design', pricing_model: 'Freemium',
    tags: ['design', 'graphics', 'templates', 'social media'], badges: ['community_pick'],
    upvote_count: 4560, review_count: 2100, average_rating: 4.7, rank_score: 9300,
    is_featured: false, is_verified: true, is_pro: false,
    launched_at: '2013-01-01', created_at: '2013-01-01', updated_at: '2026-03-01',
  },
  {
    id: '17', slug: 'zapier', name: 'Zapier', tagline: 'Automate your work across 6,000+ apps',
    description: 'Zapier is an online automation tool that connects your apps and services. You can connect two or more apps to automate repetitive tasks without coding.',
    logo_url: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663413324407/3XGasP8CcX57JRU5Ai2Hv7/final_zapier_97523b8c.png',
    website_url: 'https://zapier.com', category: 'AI Productivity', pricing_model: 'Freemium',
    tags: ['automation', 'integrations', 'workflow', 'no-code'], badges: ['top_rated'],
    upvote_count: 3120, review_count: 1876, average_rating: 4.6, rank_score: 9200,
    is_featured: false, is_verified: true, is_pro: false,
    launched_at: '2011-10-01', created_at: '2011-10-01', updated_at: '2026-03-01',
  },
  {
    id: '18', slug: 'cal-com', name: 'Cal.com', tagline: 'Open source scheduling infrastructure',
    description: 'Cal.com is the open source Calendly alternative. Schedule meetings, manage availability, and integrate with your existing tools — all with full data ownership.',
    logo_url: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663413324407/3XGasP8CcX57JRU5Ai2Hv7/final_cal_bf1515ae.png',
    website_url: 'https://cal.com', category: 'AI Productivity', pricing_model: 'Freemium',
    tags: ['scheduling', 'calendar', 'open source', 'meetings'], badges: ['new_launch', 'trending'],
    upvote_count: 1450, review_count: 432, average_rating: 4.6, rank_score: 8600,
    is_featured: false, is_verified: true, is_pro: false,
    launched_at: '2021-09-01', created_at: '2021-09-01', updated_at: '2026-03-01',
  },
];

export const MOCK_LEADERBOARD: LeaderboardEntry[] = MOCK_TOOLS.map((tool, i) => ({
  rank: i + 1,
  tool,
  rank_change: [2, -1, 0, 3, 1, -2, 0, -1][i] ?? 0,
  period: 'weekly',
}));

export const MOCK_REVIEWS: Review[] = [
  {
    id: 'r1', tool_id: '1', user_id: 'u1', rating: 5,
    title: 'Best AI writing tool I\'ve used',
    body: 'Writesonic has completely transformed how I create content. The quality is exceptional and it saves me hours every week.',
    pros: 'Fast, high quality output, great SEO features',
    cons: 'Can be a bit pricey for solo creators',
    use_case: 'Blog content and social media copy',
    is_verified_purchase: true, helpful_count: 42,
    created_at: '2026-02-15',
    user: { id: 'u1', name: 'Sarah Chen', avatar_url: undefined, role: 'Content Marketer', company: 'GrowthLabs' },
  },
  {
    id: 'r2', tool_id: '1', user_id: 'u2', rating: 4,
    title: 'Solid tool with room to grow',
    body: 'Overall very happy with Writesonic. The AI output is consistently good and the team ships updates regularly.',
    pros: 'Reliable, good templates, responsive support',
    cons: 'UI could be more intuitive',
    is_verified_purchase: true, helpful_count: 18,
    created_at: '2026-01-28',
    user: { id: 'u2', name: 'Marcus Rivera', role: 'Founder', company: 'Startup Studio' },
    founder_reply: {
      body: 'Thanks Marcus! We\'re actively working on a UI refresh — stay tuned for updates in Q2.',
      created_at: '2026-01-30',
    },
  },
];

export const CATEGORIES = [
  { name: 'All', icon: '✦', count: 18 },
  { name: 'AI Productivity', icon: '⚡', count: 4 },
  { name: 'Design', icon: '🎨', count: 3 },
  { name: 'AI Code', icon: '💻', count: 2 },
  { name: 'AI Video', icon: '🎬', count: 2 },
  { name: 'AI Writing', icon: '✍️', count: 2 },
  { name: 'Developer Tools', icon: '🛠️', count: 2 },
  { name: 'AI Image', icon: '🖼️', count: 1 },
  { name: 'AI Analytics', icon: '📊', count: 1 },
  { name: 'Project Management', icon: '📋', count: 1 },
];
