import type { Tool, Review, LeaderboardEntry } from './types';

export const MOCK_TOOLS: Tool[] = [
  // ── AI Chat (5) ──────────────────────────────────────────────────────────
  {
    id: '1', slug: 'chatgpt', name: 'ChatGPT', tagline: 'The world\'s most popular AI assistant',
    description: 'ChatGPT is an AI-powered chatbot developed by OpenAI. It uses large language models to generate human-like text responses, assist with writing, coding, analysis, and much more.',
    logo_url: 'https://www.google.com/s2/favicons?domain=chat.openai.com&sz=128',
    website_url: 'https://chat.openai.com', category: 'AI Productivity', pricing_model: 'Freemium',
    tags: ['AI', 'chat', 'assistant', 'GPT'], badges: ['top_rated', 'featured'],
    upvote_count: 8420, review_count: 3241, average_rating: 4.8, rank_score: 9980, weekly_rank_change: 12,
    is_featured: true, is_verified: true, is_pro: false,
    launched_at: '2022-11-30', created_at: '2022-11-30', updated_at: '2026-03-07',
  },
  {
    id: '2', slug: 'claude', name: 'Claude', tagline: 'AI assistant by Anthropic',
    description: 'Claude is a next-generation AI assistant built by Anthropic. It is trained to be safe, accurate, and helpful for complex reasoning, analysis, and writing tasks.',
    logo_url: 'https://www.google.com/s2/favicons?domain=claude.ai&sz=128',
    website_url: 'https://claude.ai', category: 'AI Productivity', pricing_model: 'Freemium',
    tags: ['AI', 'assistant', 'writing', 'reasoning'], badges: ['top_rated', 'featured'],
    upvote_count: 3760, review_count: 1089, average_rating: 4.8, rank_score: 9600, weekly_rank_change: 8,
    is_featured: true, is_verified: false, is_pro: false,
    launched_at: '2023-03-14', created_at: '2023-03-14', updated_at: '2026-03-01',
  },
  {
    id: '3', slug: 'perplexity', name: 'Perplexity AI', tagline: 'AI-powered search engine',
    description: 'Perplexity AI is a conversational search engine that uses AI to provide direct answers to questions with cited sources from the web.',
    logo_url: 'https://www.google.com/s2/favicons?domain=perplexity.ai&sz=128',
    website_url: 'https://perplexity.ai', category: 'AI Analytics', pricing_model: 'Freemium',
    tags: ['search', 'research', 'AI', 'answers'], badges: ['best_value'],
    upvote_count: 1543, review_count: 421, average_rating: 4.6, rank_score: 8750, weekly_rank_change: 26,
    is_featured: false, is_verified: true, is_pro: false,
    screenshot_url: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663413324407/3XGasP8CcX57JRU5Ai2Hv7/perplexity-screenshot_8d34c5c4.png',
    launched_at: '2022-12-07', created_at: '2022-12-07', updated_at: '2026-03-04',
  },
  {
    id: '4', slug: 'gemini', name: 'Gemini', tagline: 'Google\'s most capable AI model',
    description: 'Gemini is Google\'s most capable and general AI model, built to be multimodal from the ground up. It can understand and combine different types of information.',
    logo_url: 'https://www.google.com/s2/favicons?domain=gemini.google.com&sz=128',
    website_url: 'https://gemini.google.com', category: 'AI Productivity', pricing_model: 'Freemium',
    tags: ['AI', 'chat', 'Google', 'multimodal'], badges: ['new_launch', 'trending'],
    upvote_count: 2890, review_count: 876, average_rating: 4.5, rank_score: 9100, weekly_rank_change: 3,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2023-12-06', created_at: '2023-12-06', updated_at: '2026-03-01',
  },
  {
    id: '5', slug: 'microsoft-copilot', name: 'Microsoft Copilot', tagline: 'Your everyday AI companion',
    description: 'Microsoft Copilot is an AI companion integrated across Microsoft 365 apps, helping you write, summarize, analyze, and create content across Word, Excel, PowerPoint, and Teams.',
    logo_url: 'https://www.google.com/s2/favicons?domain=copilot.microsoft.com&sz=128',
    website_url: 'https://copilot.microsoft.com', category: 'AI Productivity', pricing_model: 'Freemium',
    tags: ['AI', 'Microsoft', 'productivity', 'Office'], badges: ['featured'],
    upvote_count: 2100, review_count: 654, average_rating: 4.4, rank_score: 8900, weekly_rank_change: 19,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2023-09-26', created_at: '2023-09-26', updated_at: '2026-03-01',
  },

  // ── AI Writing (11) ──────────────────────────────────────────────────────
  {
    id: '6', slug: 'jasper', name: 'Jasper', tagline: 'AI content platform for marketing teams',
    description: 'Jasper is an AI content platform that helps marketing teams create on-brand content faster. From blog posts to ad copy, Jasper helps you scale content production.',
    logo_url: 'https://www.google.com/s2/favicons?domain=jasper.ai&sz=128',
    website_url: 'https://jasper.ai', category: 'AI Writing', pricing_model: 'Paid',
    tags: ['writing', 'marketing', 'content', 'AI'], badges: ['top_rated', 'editors_pick'],
    upvote_count: 2340, review_count: 876, average_rating: 4.6, rank_score: 9200, weekly_rank_change: 6,
    is_featured: true, is_verified: false, is_pro: true,
    promotional_banner: 'Get 7 days free — no credit card required',
    promotional_cta: 'Start Free Trial',
    launched_at: '2021-01-01', created_at: '2021-01-01', updated_at: '2026-03-01',
  },
  {
    id: '7', slug: 'copy-ai', name: 'Copy.ai', tagline: 'AI-powered copywriting for growth',
    description: 'Copy.ai is an AI writing tool that helps you create marketing copy, blog content, social media posts, and more in seconds using advanced language models.',
    logo_url: 'https://www.google.com/s2/favicons?domain=copy.ai&sz=128',
    website_url: 'https://copy.ai', category: 'AI Writing', pricing_model: 'Freemium',
    tags: ['copywriting', 'marketing', 'AI', 'content'], badges: ['best_value'],
    upvote_count: 1890, review_count: 654, average_rating: 4.4, rank_score: 8700, weekly_rank_change: -2,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2020-10-01', created_at: '2020-10-01', updated_at: '2026-02-28',
  },
  {
    id: '8', slug: 'writesonic', name: 'Writesonic', tagline: 'AI writing assistant for teams',
    description: 'Writesonic is an AI-powered writing platform that helps you create SEO-optimized content, ads, emails, and more in seconds.',
    logo_url: 'https://www.google.com/s2/favicons?domain=writesonic.com&sz=128',
    website_url: 'https://writesonic.com', category: 'AI Writing', pricing_model: 'Freemium',
    tags: ['writing', 'SEO', 'content', 'AI'], badges: ['top_rated', 'featured'],
    upvote_count: 1284, review_count: 342, average_rating: 4.7, rank_score: 9820, weekly_rank_change: 22,
    is_featured: true, is_verified: false, is_pro: true,
    promotional_banner: 'Get 3 months free with code LAUNCH2026',
    promotional_cta: 'Claim Offer',
    launched_at: '2020-10-01', created_at: '2020-10-01', updated_at: '2026-03-01',
  },
  {
    id: '9', slug: 'rytr', name: 'Rytr', tagline: 'AI writing assistant for everyone',
    description: 'Rytr is an AI writing assistant that helps you create high-quality content in just a few seconds, at a fraction of the cost. Supports 40+ use cases and 30+ languages.',
    logo_url: 'https://www.google.com/s2/favicons?domain=rytr.me&sz=128',
    website_url: 'https://rytr.me', category: 'AI Writing', pricing_model: 'Freemium',
    tags: ['writing', 'AI', 'content', 'affordable'], badges: ['best_value'],
    upvote_count: 987, review_count: 312, average_rating: 4.3, rank_score: 8200, weekly_rank_change: 1,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2021-04-01', created_at: '2021-04-01', updated_at: '2026-02-15',
  },
  {
    id: '10', slug: 'grammarly', name: 'Grammarly', tagline: 'AI writing and grammar assistant',
    description: 'Grammarly is an AI-powered writing assistant that helps you write clearly and effectively. It checks grammar, spelling, style, and tone across all your apps.',
    logo_url: 'https://www.google.com/s2/favicons?domain=grammarly.com&sz=128',
    website_url: 'https://grammarly.com', category: 'AI Writing', pricing_model: 'Freemium',
    tags: ['writing', 'grammar', 'AI', 'productivity'], badges: ['best_value', 'community_pick'],
    upvote_count: 2890, review_count: 1432, average_rating: 4.5, rank_score: 8900, weekly_rank_change: 11,
    is_featured: false, is_verified: true, is_pro: false,
    launched_at: '2009-07-01', created_at: '2009-07-01', updated_at: '2026-03-01',
  },
  {
    id: '11', slug: 'quillbot', name: 'QuillBot', tagline: 'AI paraphrasing and writing tool',
    description: 'QuillBot is an AI-powered paraphrasing tool that helps you rewrite, summarize, and improve your writing. Used by millions of students and professionals worldwide.',
    logo_url: 'https://www.google.com/s2/favicons?domain=quillbot.com&sz=128',
    website_url: 'https://quillbot.com', category: 'AI Writing', pricing_model: 'Freemium',
    tags: ['paraphrasing', 'writing', 'AI', 'summarize'], badges: ['best_value'],
    upvote_count: 1650, review_count: 543, average_rating: 4.4, rank_score: 8500, weekly_rank_change: -4,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2017-01-01', created_at: '2017-01-01', updated_at: '2026-02-20',
  },
  {
    id: '12', slug: 'wordtune', name: 'Wordtune', tagline: 'Rewrite and improve your writing with AI',
    description: 'Wordtune is an AI writing companion that helps you say exactly what you mean. It understands context and meaning to suggest rewrites that improve clarity and tone.',
    logo_url: 'https://www.google.com/s2/favicons?domain=wordtune.com&sz=128',
    website_url: 'https://wordtune.com', category: 'AI Writing', pricing_model: 'Freemium',
    tags: ['writing', 'rewriting', 'AI', 'clarity'], badges: [],
    upvote_count: 890, review_count: 234, average_rating: 4.2, rank_score: 7900, weekly_rank_change: 7,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2020-01-01', created_at: '2020-01-01', updated_at: '2026-02-10',
  },
  {
    id: '13', slug: 'sudowrite', name: 'Sudowrite', tagline: 'AI writing partner for fiction writers',
    description: 'Sudowrite is an AI writing tool built specifically for creative writers and novelists. It helps you brainstorm, draft, and revise your fiction with powerful AI assistance.',
    logo_url: 'https://www.google.com/s2/favicons?domain=sudowrite.com&sz=128',
    website_url: 'https://sudowrite.com', category: 'AI Writing', pricing_model: 'Paid',
    tags: ['fiction', 'creative writing', 'AI', 'novels'], badges: ['editors_pick'],
    upvote_count: 760, review_count: 198, average_rating: 4.5, rank_score: 8100, weekly_rank_change: 18,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2020-11-01', created_at: '2020-11-01', updated_at: '2026-02-01',
  },
  {
    id: '14', slug: 'hypotenuse-ai', name: 'Hypotenuse AI', tagline: 'AI content for e-commerce at scale',
    description: 'Hypotenuse AI helps e-commerce brands generate product descriptions, blog posts, and marketing copy at scale using AI trained on high-converting content.',
    logo_url: 'https://www.google.com/s2/favicons?domain=hypotenuse.ai&sz=128',
    website_url: 'https://hypotenuse.ai', category: 'AI Writing', pricing_model: 'Paid',
    tags: ['e-commerce', 'product descriptions', 'AI', 'content'], badges: [],
    upvote_count: 540, review_count: 143, average_rating: 4.3, rank_score: 7600, weekly_rank_change: 2,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2020-08-01', created_at: '2020-08-01', updated_at: '2026-01-15',
  },
  {
    id: '15', slug: 'textcortex', name: 'TextCortex', tagline: 'AI writing assistant with custom personas',
    description: 'TextCortex is an AI writing assistant that lets you create custom AI personas trained on your brand voice. Generate content that sounds like you, at scale.',
    logo_url: 'https://www.google.com/s2/favicons?domain=textcortex.com&sz=128',
    website_url: 'https://textcortex.com', category: 'AI Writing', pricing_model: 'Freemium',
    tags: ['writing', 'brand voice', 'AI', 'personas'], badges: ['new_launch'],
    upvote_count: 430, review_count: 112, average_rating: 4.2, rank_score: 7400, weekly_rank_change: 14,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2021-06-01', created_at: '2021-06-01', updated_at: '2026-01-20',
  },
  {
    id: '16', slug: 'anyword', name: 'Anyword', tagline: 'Predictive AI copywriting platform',
    description: 'Anyword uses predictive performance scores to help marketers create copy that converts. It analyzes your audience and predicts which messaging will perform best.',
    logo_url: 'https://www.google.com/s2/favicons?domain=anyword.com&sz=128',
    website_url: 'https://anyword.com', category: 'AI Writing', pricing_model: 'Paid',
    tags: ['copywriting', 'marketing', 'AI', 'conversion'], badges: ['trending'],
    upvote_count: 670, review_count: 187, average_rating: 4.4, rank_score: 8000, weekly_rank_change: -1,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2013-01-01', created_at: '2013-01-01', updated_at: '2026-02-05',
  },

  // ── AI Image (10) ────────────────────────────────────────────────────────
  {
    id: '17', slug: 'midjourney', name: 'Midjourney', tagline: 'AI image generation for creatives',
    description: 'Midjourney is an independent research lab exploring new mediums of thought and expanding the imaginative powers of the human species through AI image generation.',
    logo_url: 'https://www.google.com/s2/favicons?domain=midjourney.com&sz=128',
    website_url: 'https://midjourney.com', category: 'AI Image', pricing_model: 'Paid',
    tags: ['image', 'art', 'creative', 'AI'], badges: ['top_rated', 'community_pick'],
    upvote_count: 3421, review_count: 1204, average_rating: 4.9, rank_score: 9580, weekly_rank_change: 9,
    is_featured: true, is_verified: true, is_pro: false,
    launched_at: '2022-07-12', created_at: '2022-07-12', updated_at: '2026-03-05',
  },
  {
    id: '18', slug: 'leonardo-ai', name: 'Leonardo AI', tagline: 'AI image generation for game assets',
    description: 'Leonardo AI is a powerful AI image generation platform with fine-tuned models for game assets, concept art, and creative projects. Train your own custom models.',
    logo_url: 'https://www.google.com/s2/favicons?domain=leonardo.ai&sz=128',
    website_url: 'https://leonardo.ai', category: 'AI Image', pricing_model: 'Freemium',
    tags: ['image', 'game assets', 'AI', 'art'], badges: ['trending', 'new_launch'],
    upvote_count: 1870, review_count: 543, average_rating: 4.6, rank_score: 9000, weekly_rank_change: 25,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2022-11-01', created_at: '2022-11-01', updated_at: '2026-03-01',
  },
  {
    id: '19', slug: 'dreamstudio', name: 'DreamStudio', tagline: 'Stable Diffusion image generation',
    description: 'DreamStudio is the official interface for Stable Diffusion by Stability AI. Generate photorealistic images, artwork, and illustrations from text prompts.',
    logo_url: 'https://www.google.com/s2/favicons?domain=dreamstudio.ai&sz=128',
    website_url: 'https://dreamstudio.ai', category: 'AI Image', pricing_model: 'Paid',
    tags: ['image', 'Stable Diffusion', 'AI', 'art'], badges: [],
    upvote_count: 1230, review_count: 387, average_rating: 4.3, rank_score: 8300, weekly_rank_change: 5,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2022-08-22', created_at: '2022-08-22', updated_at: '2026-02-15',
  },
  {
    id: '20', slug: 'playground-ai', name: 'Playground AI', tagline: 'Free AI image generation playground',
    description: 'Playground AI is a free-to-use online AI image creator. Use it to create art, social media posts, presentations, posters, videos, logos and more.',
    logo_url: 'https://www.google.com/s2/favicons?domain=playground.com&sz=128',
    website_url: 'https://playground.com', category: 'AI Image', pricing_model: 'Freemium',
    tags: ['image', 'free', 'AI', 'art'], badges: ['best_value'],
    upvote_count: 980, review_count: 276, average_rating: 4.2, rank_score: 7800, weekly_rank_change: 13,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2022-09-01', created_at: '2022-09-01', updated_at: '2026-01-20',
  },
  {
    id: '21', slug: 'dalle', name: 'DALL-E 3', tagline: 'OpenAI\'s image generation model',
    description: 'DALL-E 3 is OpenAI\'s most advanced image generation model. It creates highly accurate images from text descriptions and is integrated directly into ChatGPT.',
    logo_url: 'https://www.google.com/s2/favicons?domain=openai.com&sz=128',
    website_url: 'https://openai.com/dall-e-3', category: 'AI Image', pricing_model: 'Paid',
    tags: ['image', 'OpenAI', 'AI', 'generation'], badges: ['top_rated'],
    upvote_count: 2100, review_count: 765, average_rating: 4.7, rank_score: 9200, weekly_rank_change: -3,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2023-10-03', created_at: '2023-10-03', updated_at: '2026-03-01',
  },
  {
    id: '22', slug: 'adobe-firefly', name: 'Adobe Firefly', tagline: 'AI image generation by Adobe',
    description: 'Adobe Firefly is a family of creative generative AI models designed for safe commercial use. Generate images, text effects, and more with AI trained on licensed content.',
    logo_url: 'https://www.google.com/s2/favicons?domain=adobe.com&sz=128',
    website_url: 'https://firefly.adobe.com', category: 'AI Image', pricing_model: 'Freemium',
    tags: ['image', 'Adobe', 'AI', 'commercial'], badges: ['editors_pick'],
    upvote_count: 1560, review_count: 432, average_rating: 4.5, rank_score: 8700, weekly_rank_change: 16,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2023-03-21', created_at: '2023-03-21', updated_at: '2026-03-01',
  },
  {
    id: '23', slug: 'nightcafe', name: 'NightCafe', tagline: 'AI art generation with community',
    description: 'NightCafe Creator is an AI art generator app with multiple methods of AI art generation. It has a thriving community of AI art enthusiasts.',
    logo_url: 'https://www.google.com/s2/favicons?domain=nightcafe.studio&sz=128',
    website_url: 'https://creator.nightcafe.studio', category: 'AI Image', pricing_model: 'Freemium',
    tags: ['image', 'art', 'community', 'AI'], badges: ['community_pick'],
    upvote_count: 870, review_count: 234, average_rating: 4.3, rank_score: 7700, weekly_rank_change: 4,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2019-12-01', created_at: '2019-12-01', updated_at: '2026-01-15',
  },
  {
    id: '24', slug: 'artsmart', name: 'ArtSmart', tagline: 'AI image generation for marketers',
    description: 'ArtSmart is an AI image generation platform built for marketers and businesses. Create product images, marketing visuals, and brand assets with AI.',
    logo_url: 'https://www.google.com/s2/favicons?domain=artsmart.ai&sz=128',
    website_url: 'https://artsmart.ai', category: 'AI Image', pricing_model: 'Paid',
    tags: ['image', 'marketing', 'AI', 'business'], badges: [],
    upvote_count: 430, review_count: 98, average_rating: 4.1, rank_score: 7200, weekly_rank_change: 21,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2022-05-01', created_at: '2022-05-01', updated_at: '2025-12-01',
  },
  {
    id: '25', slug: 'mage-space', name: 'Mage.space', tagline: 'Fast, free Stable Diffusion',
    description: 'Mage.space is a fast, free, and uncensored Stable Diffusion image generator. Create any image you can imagine with state-of-the-art AI models.',
    logo_url: 'https://www.google.com/s2/favicons?domain=mage.space&sz=128',
    website_url: 'https://www.mage.space', category: 'AI Image', pricing_model: 'Freemium',
    tags: ['image', 'free', 'Stable Diffusion', 'AI'], badges: ['best_value'],
    upvote_count: 560, review_count: 143, average_rating: 4.2, rank_score: 7500, weekly_rank_change: 0,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2022-10-01', created_at: '2022-10-01', updated_at: '2025-11-01',
  },
  {
    id: '26', slug: 'bluewillow', name: 'BlueWillow', tagline: 'Free AI image generation',
    description: 'BlueWillow is a free AI image generation tool that creates stunning artwork from text prompts. Accessible via Discord with no subscription required.',
    logo_url: 'https://www.google.com/s2/favicons?domain=bluewillow.ai&sz=128',
    website_url: 'https://www.bluewillow.ai', category: 'AI Image', pricing_model: 'Free',
    tags: ['image', 'free', 'Discord', 'AI'], badges: ['best_value'],
    upvote_count: 340, review_count: 87, average_rating: 4.0, rank_score: 6900, weekly_rank_change: 10,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2022-12-01', created_at: '2022-12-01', updated_at: '2025-10-01',
  },

  // ── AI Video (10) ────────────────────────────────────────────────────────
  {
    id: '27', slug: 'synthesia', name: 'Synthesia', tagline: 'AI video generation with avatars',
    description: 'Synthesia is an AI video generation platform that lets you create professional videos with AI avatars from text. No cameras, microphones, or studios required.',
    logo_url: 'https://www.google.com/s2/favicons?domain=synthesia.io&sz=128',
    website_url: 'https://synthesia.io', category: 'AI Video', pricing_model: 'Paid',
    tags: ['video', 'avatars', 'AI', 'training'], badges: ['top_rated', 'editors_pick'],
    upvote_count: 1890, review_count: 654, average_rating: 4.7, rank_score: 9100, weekly_rank_change: -5,
    is_featured: true, is_verified: true, is_pro: true,
    launched_at: '2017-01-01', created_at: '2017-01-01', updated_at: '2026-03-01',
  },
  {
    id: '28', slug: 'pictory', name: 'Pictory', tagline: 'Turn scripts into videos with AI',
    description: 'Pictory is an AI video creation tool that turns your scripts, blog posts, and articles into engaging short videos automatically.',
    logo_url: 'https://www.google.com/s2/favicons?domain=pictory.ai&sz=128',
    website_url: 'https://pictory.ai', category: 'AI Video', pricing_model: 'Paid',
    tags: ['video', 'script', 'AI', 'marketing'], badges: ['trending'],
    upvote_count: 1120, review_count: 345, average_rating: 4.4, rank_score: 8400, weekly_rank_change: 17,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2021-01-01', created_at: '2021-01-01', updated_at: '2026-02-15',
  },
  {
    id: '29', slug: 'heygen', name: 'HeyGen', tagline: 'AI video with personalized avatars',
    description: 'HeyGen is an AI video platform that enables businesses to create studio-quality videos with personalized AI avatars and voice cloning at scale.',
    logo_url: 'https://www.google.com/s2/favicons?domain=heygen.com&sz=128',
    website_url: 'https://heygen.com', category: 'AI Video', pricing_model: 'Freemium',
    tags: ['video', 'avatars', 'voice cloning', 'AI'], badges: ['new_launch', 'trending'],
    upvote_count: 1540, review_count: 432, average_rating: 4.6, rank_score: 8900, weekly_rank_change: 8,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2022-01-01', created_at: '2022-01-01', updated_at: '2026-03-01',
  },
  {
    id: '30', slug: 'invideo-ai', name: 'InVideo AI', tagline: 'Create videos from text with AI',
    description: 'InVideo AI is an online video creation platform that lets you create professional videos from text prompts, scripts, and articles in minutes.',
    logo_url: 'https://www.google.com/s2/favicons?domain=invideo.io&sz=128',
    website_url: 'https://invideo.io', category: 'AI Video', pricing_model: 'Freemium',
    tags: ['video', 'AI', 'creation', 'marketing'], badges: ['best_value'],
    upvote_count: 980, review_count: 287, average_rating: 4.3, rank_score: 8000, weekly_rank_change: 3,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2019-01-01', created_at: '2019-01-01', updated_at: '2026-02-01',
  },
  {
    id: '31', slug: 'runway-ml', name: 'Runway ML', tagline: 'AI-powered creative tools for video',
    description: 'Runway is an applied AI research company building the next era of art, entertainment and human creativity. Gen-2 enables text-to-video generation.',
    logo_url: 'https://www.google.com/s2/favicons?domain=runwayml.com&sz=128',
    website_url: 'https://runwayml.com', category: 'AI Video', pricing_model: 'Freemium',
    tags: ['video', 'generative AI', 'creative', 'text-to-video'], badges: ['editors_pick', 'trending'],
    upvote_count: 2100, review_count: 654, average_rating: 4.6, rank_score: 9000, weekly_rank_change: 20,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2018-01-01', created_at: '2018-01-01', updated_at: '2026-03-01',
  },
  {
    id: '32', slug: 'descript', name: 'Descript', tagline: 'Edit video like a doc',
    description: 'Descript is the only tool you need to write, record, transcribe, edit, collaborate, and share your videos and podcasts.',
    logo_url: 'https://www.google.com/s2/favicons?domain=descript.com&sz=128',
    website_url: 'https://descript.com', category: 'AI Video', pricing_model: 'Freemium',
    tags: ['video', 'podcast', 'editing', 'transcription'], badges: ['verified'],
    upvote_count: 987, review_count: 312, average_rating: 4.5, rank_score: 8920, weekly_rank_change: -2,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2019-06-01', created_at: '2019-06-01', updated_at: '2026-02-20',
  },
  {
    id: '33', slug: 'loom', name: 'Loom', tagline: 'Async video messaging for work',
    description: 'Loom is a video messaging tool that helps you get your message across through instantly shareable videos.',
    logo_url: 'https://www.google.com/s2/favicons?domain=loom.com&sz=128',
    website_url: 'https://loom.com', category: 'AI Video', pricing_model: 'Freemium',
    tags: ['video', 'async', 'communication', 'screen recording'], badges: [],
    upvote_count: 876, review_count: 289, average_rating: 4.4, rank_score: 8320, weekly_rank_change: 6,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2016-01-01', created_at: '2016-01-01', updated_at: '2026-02-15',
  },
  {
    id: '34', slug: 'kaiber', name: 'Kaiber', tagline: 'AI video generation for artists',
    description: 'Kaiber is an AI video generation engine that enables artists and creators to transform their ideas into stunning visual stories.',
    logo_url: 'https://www.google.com/s2/favicons?domain=kaiber.ai&sz=128',
    website_url: 'https://kaiber.ai', category: 'AI Video', pricing_model: 'Paid',
    tags: ['video', 'art', 'AI', 'creative'], badges: ['new_launch'],
    upvote_count: 540, review_count: 143, average_rating: 4.2, rank_score: 7600, weekly_rank_change: 14,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2022-09-01', created_at: '2022-09-01', updated_at: '2025-12-01',
  },
  {
    id: '35', slug: 'veed', name: 'VEED', tagline: 'Online video editor with AI features',
    description: 'VEED is an online video editing platform with powerful AI features including auto-subtitles, background removal, and AI avatars for quick video creation.',
    logo_url: 'https://www.google.com/s2/favicons?domain=veed.io&sz=128',
    website_url: 'https://veed.io', category: 'AI Video', pricing_model: 'Freemium',
    tags: ['video', 'editing', 'subtitles', 'AI'], badges: ['best_value'],
    upvote_count: 1230, review_count: 398, average_rating: 4.4, rank_score: 8500, weekly_rank_change: 1,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2018-01-01', created_at: '2018-01-01', updated_at: '2026-02-01',
  },
  {
    id: '36', slug: 'capcut-ai', name: 'CapCut AI', tagline: 'AI-powered video editor for creators',
    description: 'CapCut is an all-in-one creative platform powered by AI that enables video editing, image design, and content creation for social media.',
    logo_url: 'https://www.google.com/s2/favicons?domain=capcut.com&sz=128',
    website_url: 'https://capcut.com', category: 'AI Video', pricing_model: 'Freemium',
    tags: ['video', 'social media', 'AI', 'editing'], badges: ['community_pick', 'trending'],
    upvote_count: 2340, review_count: 876, average_rating: 4.5, rank_score: 8800, weekly_rank_change: 11,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2020-04-01', created_at: '2020-04-01', updated_at: '2026-03-01',
  },

  // ── AI Voice (5) ─────────────────────────────────────────────────────────
  {
    id: '37', slug: 'elevenlabs', name: 'ElevenLabs', tagline: 'AI voice generation and cloning',
    description: 'ElevenLabs is an AI voice technology company that creates the most realistic, versatile, and contextually-aware AI audio. Clone any voice or choose from 900+ voices.',
    logo_url: 'https://www.google.com/s2/favicons?domain=elevenlabs.io&sz=128',
    website_url: 'https://elevenlabs.io', category: 'AI Audio', pricing_model: 'Freemium',
    tags: ['voice', 'text-to-speech', 'AI', 'cloning'], badges: ['top_rated', 'trending'],
    upvote_count: 2890, review_count: 987, average_rating: 4.8, rank_score: 9400, weekly_rank_change: -6,
    is_featured: true, is_verified: true, is_pro: false,
    launched_at: '2022-01-01', created_at: '2022-01-01', updated_at: '2026-03-01',
  },
  {
    id: '38', slug: 'murf-ai', name: 'Murf AI', tagline: 'Studio-quality AI voiceovers',
    description: 'Murf AI is a text-to-speech platform that lets you create studio-quality voiceovers in minutes. Choose from 120+ AI voices in 20+ languages.',
    logo_url: 'https://www.google.com/s2/favicons?domain=murf.ai&sz=128',
    website_url: 'https://murf.ai', category: 'AI Audio', pricing_model: 'Freemium',
    tags: ['voice', 'text-to-speech', 'AI', 'voiceover'], badges: ['editors_pick'],
    upvote_count: 1230, review_count: 432, average_rating: 4.5, rank_score: 8600, weekly_rank_change: 9,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2020-01-01', created_at: '2020-01-01', updated_at: '2026-02-15',
  },
  {
    id: '39', slug: 'playht', name: 'PlayHT', tagline: 'AI voice generator and text-to-speech',
    description: 'PlayHT is an AI voice generator that creates ultra-realistic text-to-speech voices. Generate audio from text with natural-sounding AI voices in 900+ voices.',
    logo_url: 'https://www.google.com/s2/favicons?domain=play.ht&sz=128',
    website_url: 'https://play.ht', category: 'AI Audio', pricing_model: 'Freemium',
    tags: ['voice', 'text-to-speech', 'AI', 'audio'], badges: [],
    upvote_count: 870, review_count: 234, average_rating: 4.3, rank_score: 8000, weekly_rank_change: 15,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2019-01-01', created_at: '2019-01-01', updated_at: '2026-01-20',
  },
  {
    id: '40', slug: 'speechify', name: 'Speechify', tagline: 'Listen to anything with AI voices',
    description: 'Speechify is the #1 text-to-speech app. Listen to docs, articles, PDFs, email — anything you read — in a natural AI voice at up to 4.5x speed.',
    logo_url: 'https://www.google.com/s2/favicons?domain=speechify.com&sz=128',
    website_url: 'https://speechify.com', category: 'AI Audio', pricing_model: 'Freemium',
    tags: ['text-to-speech', 'reading', 'AI', 'accessibility'], badges: ['community_pick'],
    upvote_count: 1560, review_count: 543, average_rating: 4.4, rank_score: 8400, weekly_rank_change: 4,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2017-01-01', created_at: '2017-01-01', updated_at: '2026-02-01',
  },
  {
    id: '41', slug: 'resemble-ai', name: 'Resemble AI', tagline: 'Custom AI voice cloning platform',
    description: 'Resemble AI is a voice cloning platform that lets you create custom AI voices for your brand. Clone any voice in minutes and generate speech at scale.',
    logo_url: 'https://www.google.com/s2/favicons?domain=resemble.ai&sz=128',
    website_url: 'https://resemble.ai', category: 'AI Audio', pricing_model: 'Paid',
    tags: ['voice cloning', 'AI', 'audio', 'enterprise'], badges: [],
    upvote_count: 540, review_count: 143, average_rating: 4.2, rank_score: 7600, weekly_rank_change: 23,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2019-01-01', created_at: '2019-01-01', updated_at: '2025-12-01',
  },

  // ── SEO (5) ──────────────────────────────────────────────────────────────
  {
    id: '42', slug: 'surfer-seo', name: 'Surfer SEO', tagline: 'Data-driven SEO content optimization',
    description: 'Surfer SEO is a cloud-based on-page optimization tool that analyzes and compares your pages against top-ranking pages to help you create content that ranks.',
    logo_url: 'https://www.google.com/s2/favicons?domain=surferseo.com&sz=128',
    website_url: 'https://surferseo.com', category: 'Marketing', pricing_model: 'Paid',
    tags: ['SEO', 'content optimization', 'AI', 'ranking'], badges: ['top_rated', 'editors_pick'],
    upvote_count: 1870, review_count: 654, average_rating: 4.7, rank_score: 9100, weekly_rank_change: 7,
    is_featured: false, is_verified: false, is_pro: true,
    launched_at: '2017-01-01', created_at: '2017-01-01', updated_at: '2026-03-01',
  },
  {
    id: '43', slug: 'frase', name: 'Frase', tagline: 'AI SEO content research and writing',
    description: 'Frase is an AI-powered SEO content tool that helps you research, write, and optimize content that ranks. Analyze SERPs and generate briefs in minutes.',
    logo_url: 'https://www.google.com/s2/favicons?domain=frase.io&sz=128',
    website_url: 'https://frase.io', category: 'Marketing', pricing_model: 'Paid',
    tags: ['SEO', 'content', 'AI', 'research'], badges: ['best_value'],
    upvote_count: 1120, review_count: 387, average_rating: 4.5, rank_score: 8600, weekly_rank_change: -1,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2018-01-01', created_at: '2018-01-01', updated_at: '2026-02-15',
  },
  {
    id: '44', slug: 'scalenut', name: 'Scalenut', tagline: 'AI SEO and content marketing platform',
    description: 'Scalenut is an AI-powered SEO and content marketing platform that helps you plan, research, create, and optimize content that ranks on Google.',
    logo_url: 'https://www.google.com/s2/favicons?domain=scalenut.com&sz=128',
    website_url: 'https://scalenut.com', category: 'Marketing', pricing_model: 'Paid',
    tags: ['SEO', 'content marketing', 'AI', 'keyword research'], badges: [],
    upvote_count: 670, review_count: 198, average_rating: 4.3, rank_score: 7900, weekly_rank_change: 12,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2020-01-01', created_at: '2020-01-01', updated_at: '2026-01-15',
  },
  {
    id: '45', slug: 'neuronwriter', name: 'NeuronWriter', tagline: 'AI content optimization for SEO',
    description: 'NeuronWriter is an AI-powered content optimization tool that uses NLP and semantic analysis to help you create content that outranks competitors.',
    logo_url: 'https://www.google.com/s2/favicons?domain=neuronwriter.com&sz=128',
    website_url: 'https://neuronwriter.com', category: 'Marketing', pricing_model: 'Paid',
    tags: ['SEO', 'NLP', 'content', 'AI'], badges: [],
    upvote_count: 430, review_count: 112, average_rating: 4.2, rank_score: 7400, weekly_rank_change: 5,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2021-01-01', created_at: '2021-01-01', updated_at: '2025-11-01',
  },
  {
    id: '46', slug: 'marketmuse', name: 'MarketMuse', tagline: 'AI content strategy and planning',
    description: 'MarketMuse is an AI-powered content intelligence platform that helps you plan, create, and optimize content at scale. Identify content gaps and opportunities.',
    logo_url: 'https://www.google.com/s2/favicons?domain=marketmuse.com&sz=128',
    website_url: 'https://marketmuse.com', category: 'Marketing', pricing_model: 'Paid',
    tags: ['SEO', 'content strategy', 'AI', 'planning'], badges: ['editors_pick'],
    upvote_count: 760, review_count: 198, average_rating: 4.4, rank_score: 8100, weekly_rank_change: 18,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2015-01-01', created_at: '2015-01-01', updated_at: '2026-01-01',
  },

  // ── Marketing (5) ────────────────────────────────────────────────────────
  {
    id: '47', slug: 'adcreative-ai', name: 'AdCreative.ai', tagline: 'AI-generated ad creatives',
    description: 'AdCreative.ai is an AI-powered platform that generates conversion-focused ad creatives and social media posts in seconds. Boost your ad performance with AI.',
    logo_url: 'https://www.google.com/s2/favicons?domain=adcreative.ai&sz=128',
    website_url: 'https://adcreative.ai', category: 'Marketing', pricing_model: 'Paid',
    tags: ['advertising', 'AI', 'creatives', 'social media'], badges: ['trending'],
    upvote_count: 1230, review_count: 398, average_rating: 4.4, rank_score: 8500, weekly_rank_change: 2,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2021-01-01', created_at: '2021-01-01', updated_at: '2026-02-15',
  },
  {
    id: '48', slug: 'ocoya', name: 'Ocoya', tagline: 'AI social media content and scheduling',
    description: 'Ocoya is an AI-powered social media management platform that helps you create, schedule, and analyze social media content across all platforms.',
    logo_url: 'https://www.google.com/s2/favicons?domain=ocoya.com&sz=128',
    website_url: 'https://ocoya.com', category: 'Marketing', pricing_model: 'Paid',
    tags: ['social media', 'scheduling', 'AI', 'content'], badges: [],
    upvote_count: 540, review_count: 143, average_rating: 4.2, rank_score: 7600, weekly_rank_change: 8,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2020-01-01', created_at: '2020-01-01', updated_at: '2025-12-01',
  },
  {
    id: '49', slug: 'predis-ai', name: 'Predis AI', tagline: 'AI social media post generator',
    description: 'Predis AI is an AI-powered social media content generator that creates posts, videos, and carousels for Instagram, Facebook, LinkedIn, and more.',
    logo_url: 'https://www.google.com/s2/favicons?domain=predis.ai&sz=128',
    website_url: 'https://predis.ai', category: 'Marketing', pricing_model: 'Freemium',
    tags: ['social media', 'AI', 'content creation', 'Instagram'], badges: ['new_launch'],
    upvote_count: 760, review_count: 198, average_rating: 4.3, rank_score: 7900, weekly_rank_change: -3,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2021-01-01', created_at: '2021-01-01', updated_at: '2026-01-01',
  },
  {
    id: '50', slug: 'smartly-io', name: 'Smartly.io', tagline: 'AI-powered social advertising platform',
    description: 'Smartly.io is an AI-powered social advertising platform that automates and optimizes your paid social campaigns across Facebook, Instagram, TikTok, and more.',
    logo_url: 'https://www.google.com/s2/favicons?domain=smartly.io&sz=128',
    website_url: 'https://smartly.io', category: 'Marketing', pricing_model: 'Paid',
    tags: ['advertising', 'social media', 'AI', 'automation'], badges: ['top_rated'],
    upvote_count: 870, review_count: 234, average_rating: 4.5, rank_score: 8300, weekly_rank_change: 16,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2013-01-01', created_at: '2013-01-01', updated_at: '2026-01-15',
  },

  // ── AI Code (5) ──────────────────────────────────────────────────────────
  {
    id: '51', slug: 'github-copilot', name: 'GitHub Copilot', tagline: 'Your AI pair programmer',
    description: 'GitHub Copilot uses AI to suggest code and entire functions in real-time, right from your editor. Trained on billions of lines of public code.',
    logo_url: 'https://www.google.com/s2/favicons?domain=github.com&sz=128',
    website_url: 'https://github.com/features/copilot', category: 'AI Code', pricing_model: 'Paid',
    tags: ['coding', 'AI', 'autocomplete', 'developer'], badges: ['top_rated', 'editors_pick'],
    upvote_count: 4210, review_count: 1532, average_rating: 4.8, rank_score: 9900, weekly_rank_change: 10,
    is_featured: true, is_verified: true, is_pro: true,
    launched_at: '2021-06-29', created_at: '2021-06-29', updated_at: '2026-03-01',
  },
  {
    id: '52', slug: 'cursor-ai', name: 'Cursor', tagline: 'The AI-first code editor',
    description: 'Cursor is the AI-first code editor. Build software faster in an editor designed for pair-programming with AI.',
    logo_url: 'https://www.google.com/s2/favicons?domain=cursor.sh&sz=128',
    website_url: 'https://cursor.sh', category: 'AI Code', pricing_model: 'Freemium',
    tags: ['coding', 'AI', 'editor', 'developer'], badges: ['trending', 'new_launch'],
    upvote_count: 2890, review_count: 743, average_rating: 4.7, rank_score: 9380, weekly_rank_change: 24,
    is_featured: true, is_verified: true, is_pro: false,
    screenshot_url: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663413324407/3XGasP8CcX57JRU5Ai2Hv7/cursor-screenshot_3363c4be.jpeg',
    launched_at: '2023-03-14', created_at: '2023-03-14', updated_at: '2026-03-07',
  },
  {
    id: '53', slug: 'codeium', name: 'Codeium', tagline: 'Free AI code completion',
    description: 'Codeium is a free AI-powered code completion tool that works in 70+ languages and 40+ editors. Get intelligent code suggestions without any cost.',
    logo_url: 'https://www.google.com/s2/favicons?domain=codeium.com&sz=128',
    website_url: 'https://codeium.com', category: 'AI Code', pricing_model: 'Freemium',
    tags: ['coding', 'AI', 'free', 'autocomplete'], badges: ['best_value'],
    upvote_count: 1890, review_count: 543, average_rating: 4.5, rank_score: 8800, weekly_rank_change: 3,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2022-01-01', created_at: '2022-01-01', updated_at: '2026-02-15',
  },
  {
    id: '54', slug: 'tabnine', name: 'Tabnine', tagline: 'AI code completion for teams',
    description: 'Tabnine is an AI code completion tool that helps developers write code faster and with fewer errors. It supports all major languages and IDEs.',
    logo_url: 'https://www.google.com/s2/favicons?domain=tabnine.com&sz=128',
    website_url: 'https://tabnine.com', category: 'AI Code', pricing_model: 'Freemium',
    tags: ['coding', 'AI', 'autocomplete', 'teams'], badges: [],
    upvote_count: 1230, review_count: 398, average_rating: 4.4, rank_score: 8400, weekly_rank_change: -4,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2018-01-01', created_at: '2018-01-01', updated_at: '2026-02-01',
  },
  {
    id: '55', slug: 'replit-ai', name: 'Replit AI', tagline: 'Build software with AI in the browser',
    description: 'Replit is an AI-powered software development platform that lets you build, run, and deploy applications from your browser. Ghostwriter AI helps you code faster.',
    logo_url: 'https://www.google.com/s2/favicons?domain=replit.com&sz=128',
    website_url: 'https://replit.com', category: 'AI Code', pricing_model: 'Freemium',
    tags: ['coding', 'AI', 'browser', 'deployment'], badges: ['community_pick'],
    upvote_count: 1560, review_count: 487, average_rating: 4.3, rank_score: 8600, weekly_rank_change: 13,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2016-01-01', created_at: '2016-01-01', updated_at: '2026-03-01',
  },

  // ── Productivity (10) ────────────────────────────────────────────────────
  {
    id: '56', slug: 'notion-ai', name: 'Notion AI', tagline: 'Your AI-powered workspace',
    description: 'Notion AI brings the power of AI directly into your Notion workspace, helping you write, summarize, brainstorm, and more.',
    logo_url: 'https://www.google.com/s2/favicons?domain=notion.so&sz=128',
    website_url: 'https://notion.so', category: 'AI Productivity', pricing_model: 'Freemium',
    tags: ['productivity', 'notes', 'AI', 'workspace'], badges: ['editors_pick'],
    upvote_count: 2156, review_count: 891, average_rating: 4.8, rank_score: 9650, weekly_rank_change: 6,
    is_featured: true, is_verified: true, is_pro: false,
    launched_at: '2023-11-01', created_at: '2023-11-01', updated_at: '2026-02-28',
  },
  {
    id: '57', slug: 'taskade', name: 'Taskade', tagline: 'AI-powered team productivity',
    description: 'Taskade is an AI-powered productivity platform for teams. Create tasks, notes, mind maps, and workflows with AI assistance built in.',
    logo_url: 'https://www.google.com/s2/favicons?domain=taskade.com&sz=128',
    website_url: 'https://taskade.com', category: 'AI Productivity', pricing_model: 'Freemium',
    tags: ['productivity', 'tasks', 'AI', 'teams'], badges: ['new_launch'],
    upvote_count: 870, review_count: 234, average_rating: 4.4, rank_score: 8200, weekly_rank_change: 19,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2017-01-01', created_at: '2017-01-01', updated_at: '2026-02-01',
  },
  {
    id: '58', slug: 'mem-ai', name: 'Mem AI', tagline: 'Self-organizing AI workspace',
    description: 'Mem is the world\'s first AI-powered workspace that is self-organizing. It learns from your notes and automatically surfaces relevant information when you need it.',
    logo_url: 'https://www.google.com/s2/favicons?domain=mem.ai&sz=128',
    website_url: 'https://mem.ai', category: 'AI Productivity', pricing_model: 'Freemium',
    tags: ['notes', 'AI', 'knowledge management', 'workspace'], badges: ['trending'],
    upvote_count: 760, review_count: 198, average_rating: 4.3, rank_score: 7900, weekly_rank_change: 1,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2020-01-01', created_at: '2020-01-01', updated_at: '2026-01-15',
  },
  {
    id: '59', slug: 'fireflies-ai', name: 'Fireflies AI', tagline: 'AI meeting notes and transcription',
    description: 'Fireflies.ai is an AI meeting assistant that automatically records, transcribes, and summarizes your meetings. Integrates with Zoom, Teams, and Google Meet.',
    logo_url: 'https://www.google.com/s2/favicons?domain=fireflies.ai&sz=128',
    website_url: 'https://fireflies.ai', category: 'AI Productivity', pricing_model: 'Freemium',
    tags: ['meetings', 'transcription', 'AI', 'notes'], badges: ['top_rated'],
    upvote_count: 1560, review_count: 543, average_rating: 4.6, rank_score: 8900, weekly_rank_change: 9,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2016-01-01', created_at: '2016-01-01', updated_at: '2026-02-15',
  },
  {
    id: '60', slug: 'otter-ai', name: 'Otter.ai', tagline: 'AI meeting transcription and notes',
    description: 'Otter.ai is an AI-powered meeting assistant that records audio, writes notes, automatically captures slides, and generates summaries.',
    logo_url: 'https://www.google.com/s2/favicons?domain=otter.ai&sz=128',
    website_url: 'https://otter.ai', category: 'AI Productivity', pricing_model: 'Freemium',
    tags: ['meetings', 'transcription', 'AI', 'notes'], badges: ['best_value'],
    upvote_count: 1230, review_count: 432, average_rating: 4.4, rank_score: 8500, weekly_rank_change: 14,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2016-01-01', created_at: '2016-01-01', updated_at: '2026-02-01',
  },
  {
    id: '61', slug: 'supernormal', name: 'Supernormal', tagline: 'AI meeting notes for Google Meet',
    description: 'Supernormal is an AI note-taker for Google Meet that automatically generates meeting summaries, action items, and follow-ups.',
    logo_url: 'https://www.google.com/s2/favicons?domain=supernormal.com&sz=128',
    website_url: 'https://supernormal.com', category: 'AI Productivity', pricing_model: 'Freemium',
    tags: ['meetings', 'Google Meet', 'AI', 'notes'], badges: [],
    upvote_count: 540, review_count: 143, average_rating: 4.3, rank_score: 7700, weekly_rank_change: -2,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2021-01-01', created_at: '2021-01-01', updated_at: '2025-12-01',
  },
  {
    id: '62', slug: 'fathom', name: 'Fathom', tagline: 'Free AI meeting recorder for Zoom',
    description: 'Fathom is a free AI meeting recorder that records, transcribes, and summarizes your Zoom meetings so you can focus on the conversation.',
    logo_url: 'https://www.google.com/s2/favicons?domain=fathom.video&sz=128',
    website_url: 'https://fathom.video', category: 'AI Productivity', pricing_model: 'Freemium',
    tags: ['meetings', 'Zoom', 'AI', 'free'], badges: ['best_value', 'community_pick'],
    upvote_count: 1890, review_count: 654, average_rating: 4.7, rank_score: 9000, weekly_rank_change: 7,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2020-01-01', created_at: '2020-01-01', updated_at: '2026-02-15',
  },
  {
    id: '63', slug: 'krisp-ai', name: 'Krisp AI', tagline: 'AI noise cancellation for calls',
    description: 'Krisp is an AI-powered noise cancellation app that removes background noise and echo from your calls. Works with any conferencing app.',
    logo_url: 'https://www.google.com/s2/favicons?domain=krisp.ai&sz=128',
    website_url: 'https://krisp.ai', category: 'AI Productivity', pricing_model: 'Freemium',
    tags: ['noise cancellation', 'calls', 'AI', 'remote work'], badges: ['top_rated'],
    upvote_count: 1230, review_count: 432, average_rating: 4.6, rank_score: 8700, weekly_rank_change: 21,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2019-01-01', created_at: '2019-01-01', updated_at: '2026-02-01',
  },
  {
    id: '64', slug: 'zapier', name: 'Zapier', tagline: 'Automate your work across 6,000+ apps',
    description: 'Zapier is an online automation tool that connects your apps and services. You can connect two or more apps to automate repetitive tasks without coding.',
    logo_url: 'https://www.google.com/s2/favicons?domain=zapier.com&sz=128',
    website_url: 'https://zapier.com', category: 'AI Productivity', pricing_model: 'Freemium',
    tags: ['automation', 'integrations', 'workflow', 'no-code'], badges: ['top_rated'],
    upvote_count: 3120, review_count: 1876, average_rating: 4.6, rank_score: 9200, weekly_rank_change: 4,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2011-10-01', created_at: '2011-10-01', updated_at: '2026-03-01',
  },
  {
    id: '65', slug: 'avoma', name: 'Avoma', tagline: 'AI meeting lifecycle management',
    description: 'Avoma is an AI meeting assistant that helps you prepare for, record, transcribe, and analyze meetings. Get actionable insights from every conversation.',
    logo_url: 'https://www.google.com/s2/favicons?domain=avoma.com&sz=128',
    website_url: 'https://avoma.com', category: 'AI Productivity', pricing_model: 'Paid',
    tags: ['meetings', 'AI', 'sales', 'CRM'], badges: [],
    upvote_count: 430, review_count: 112, average_rating: 4.3, rank_score: 7500, weekly_rank_change: 11,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2017-01-01', created_at: '2017-01-01', updated_at: '2025-12-01',
  },

  // ── Automation (5) ───────────────────────────────────────────────────────
  {
    id: '66', slug: 'make', name: 'Make', tagline: 'Visual automation platform',
    description: 'Make (formerly Integromat) is a visual platform that lets you design, build, and automate anything from simple tasks to complex workflows without coding.',
    logo_url: 'https://www.google.com/s2/favicons?domain=make.com&sz=128',
    website_url: 'https://make.com', category: 'AI Productivity', pricing_model: 'Freemium',
    tags: ['automation', 'workflow', 'no-code', 'integrations'], badges: ['trending'],
    upvote_count: 1890, review_count: 654, average_rating: 4.6, rank_score: 9000, weekly_rank_change: -5,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2012-01-01', created_at: '2012-01-01', updated_at: '2026-02-15',
  },
  {
    id: '67', slug: 'bardeen', name: 'Bardeen', tagline: 'AI automation for repetitive tasks',
    description: 'Bardeen is an AI automation platform that helps you automate repetitive tasks in your browser. Scrape data, send emails, and connect apps without code.',
    logo_url: 'https://www.google.com/s2/favicons?domain=bardeen.ai&sz=128',
    website_url: 'https://bardeen.ai', category: 'AI Productivity', pricing_model: 'Freemium',
    tags: ['automation', 'browser', 'AI', 'scraping'], badges: ['new_launch'],
    upvote_count: 760, review_count: 198, average_rating: 4.3, rank_score: 7900, weekly_rank_change: 17,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2020-01-01', created_at: '2020-01-01', updated_at: '2026-01-01',
  },
  {
    id: '68', slug: 'relay-app', name: 'Relay.app', tagline: 'Human-in-the-loop automation',
    description: 'Relay.app is a workflow automation tool that combines AI automation with human oversight. Build workflows that know when to ask for human input.',
    logo_url: 'https://www.google.com/s2/favicons?domain=relay.app&sz=128',
    website_url: 'https://relay.app', category: 'AI Productivity', pricing_model: 'Freemium',
    tags: ['automation', 'AI', 'workflow', 'human-in-the-loop'], badges: ['trending'],
    upvote_count: 540, review_count: 143, average_rating: 4.4, rank_score: 7800, weekly_rank_change: 8,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2022-01-01', created_at: '2022-01-01', updated_at: '2026-01-15',
  },

  // ── Design (5) ───────────────────────────────────────────────────────────
  {
    id: '69', slug: 'figma', name: 'Figma', tagline: 'Collaborative interface design tool',
    description: 'Figma is a cloud-based design tool that enables teams to create, prototype, and collaborate on UI/UX designs in real time.',
    logo_url: 'https://www.google.com/s2/favicons?domain=figma.com&sz=128',
    website_url: 'https://figma.com', category: 'Design', pricing_model: 'Freemium',
    tags: ['design', 'UI/UX', 'prototyping', 'collaboration'], badges: ['top_rated', 'community_pick'],
    upvote_count: 5120, review_count: 2341, average_rating: 4.9, rank_score: 9850, weekly_rank_change: 2,
    is_featured: true, is_verified: true, is_pro: false,
    launched_at: '2016-09-27', created_at: '2016-09-27', updated_at: '2026-03-01',
  },
  {
    id: '70', slug: 'canva', name: 'Canva', tagline: 'Design anything, anywhere',
    description: 'Canva is an online design and visual communication platform with a mission to empower everyone in the world to design anything and publish anywhere.',
    logo_url: 'https://www.google.com/s2/favicons?domain=canva.com&sz=128',
    website_url: 'https://canva.com', category: 'Design', pricing_model: 'Freemium',
    tags: ['design', 'graphics', 'templates', 'social media'], badges: ['community_pick'],
    upvote_count: 4560, review_count: 2100, average_rating: 4.7, rank_score: 9300, weekly_rank_change: 15,
    is_featured: false, is_verified: true, is_pro: false,
    launched_at: '2013-01-01', created_at: '2013-01-01', updated_at: '2026-03-01',
  },
  {
    id: '71', slug: 'framer', name: 'Framer', tagline: 'Design and publish stunning sites',
    description: 'Framer is the professional website builder for creative teams. Design, prototype, and publish production-ready websites without writing code.',
    logo_url: 'https://www.google.com/s2/favicons?domain=framer.com&sz=128',
    website_url: 'https://framer.com', category: 'Design', pricing_model: 'Freemium',
    tags: ['design', 'no-code', 'website builder', 'prototyping'], badges: ['editors_pick'],
    upvote_count: 2180, review_count: 654, average_rating: 4.6, rank_score: 9100, weekly_rank_change: 5,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2014-01-01', created_at: '2014-01-01', updated_at: '2026-03-01',
  },
  {
    id: '72', slug: 'looka', name: 'Looka', tagline: 'AI logo and brand design',
    description: 'Looka is an AI-powered design platform that helps entrepreneurs and small businesses create professional logos and brand identities in minutes.',
    logo_url: 'https://www.google.com/s2/favicons?domain=looka.com&sz=128',
    website_url: 'https://looka.com', category: 'Design', pricing_model: 'Paid',
    tags: ['logo', 'branding', 'AI', 'design'], badges: ['best_value'],
    upvote_count: 870, review_count: 234, average_rating: 4.3, rank_score: 8000, weekly_rank_change: 20,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2016-01-01', created_at: '2016-01-01', updated_at: '2026-01-15',
  },
  {
    id: '73', slug: 'brandmark', name: 'Brandmark', tagline: 'AI logo design in seconds',
    description: 'Brandmark is an AI-powered logo design tool that creates unique, professional logos in seconds. Just enter your business name and get a complete brand identity.',
    logo_url: 'https://www.google.com/s2/favicons?domain=brandmark.io&sz=128',
    website_url: 'https://brandmark.io', category: 'Design', pricing_model: 'Paid',
    tags: ['logo', 'branding', 'AI', 'identity'], badges: [],
    upvote_count: 540, review_count: 143, average_rating: 4.1, rank_score: 7400, weekly_rank_change: -1,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2016-01-01', created_at: '2016-01-01', updated_at: '2025-11-01',
  },

  // ── Presentations (5) ────────────────────────────────────────────────────
  {
    id: '74', slug: 'beautiful-ai', name: 'Beautiful.ai', tagline: 'AI presentation design',
    description: 'Beautiful.ai is an AI-powered presentation tool that automatically applies design best practices to your slides, making it easy to create beautiful presentations.',
    logo_url: 'https://www.google.com/s2/favicons?domain=beautiful.ai&sz=128',
    website_url: 'https://beautiful.ai', category: 'AI Productivity', pricing_model: 'Paid',
    tags: ['presentations', 'AI', 'design', 'slides'], badges: ['editors_pick'],
    upvote_count: 1120, review_count: 345, average_rating: 4.5, rank_score: 8600, weekly_rank_change: 12,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2017-01-01', created_at: '2017-01-01', updated_at: '2026-02-01',
  },
  {
    id: '75', slug: 'gamma', name: 'Gamma', tagline: 'AI-powered presentation generator',
    description: 'Gamma is an AI-powered tool for creating beautiful presentations, documents, and web pages. Generate a complete deck from a prompt in seconds.',
    logo_url: 'https://www.google.com/s2/favicons?domain=gamma.app&sz=128',
    website_url: 'https://gamma.app', category: 'AI Productivity', pricing_model: 'Freemium',
    tags: ['presentations', 'AI', 'documents', 'web pages'], badges: ['trending', 'new_launch'],
    upvote_count: 1890, review_count: 654, average_rating: 4.6, rank_score: 9000, weekly_rank_change: 3,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2022-01-01', created_at: '2022-01-01', updated_at: '2026-03-01',
  },
  {
    id: '76', slug: 'tome', name: 'Tome', tagline: 'AI storytelling and presentation tool',
    description: 'Tome is an AI-powered storytelling format that helps you create compelling narratives and presentations. Generate entire decks from a single prompt.',
    logo_url: 'https://www.google.com/s2/favicons?domain=tome.app&sz=128',
    website_url: 'https://tome.app', category: 'AI Productivity', pricing_model: 'Freemium',
    tags: ['presentations', 'AI', 'storytelling', 'design'], badges: ['community_pick'],
    upvote_count: 1230, review_count: 398, average_rating: 4.4, rank_score: 8500, weekly_rank_change: 18,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2020-01-01', created_at: '2020-01-01', updated_at: '2026-02-01',
  },

  // ── Customer Support (5) ─────────────────────────────────────────────────
  {
    id: '77', slug: 'tidio', name: 'Tidio', tagline: 'AI customer service for e-commerce',
    description: 'Tidio is a customer service platform that combines live chat, chatbots, and email marketing. Its AI chatbot Lyro resolves up to 70% of customer queries automatically.',
    logo_url: 'https://www.google.com/s2/favicons?domain=tidio.com&sz=128',
    website_url: 'https://tidio.com', category: 'Customer Support', pricing_model: 'Freemium',
    tags: ['chatbot', 'live chat', 'AI', 'e-commerce'], badges: ['best_value', 'top_rated'],
    upvote_count: 1560, review_count: 543, average_rating: 4.6, rank_score: 8900, weekly_rank_change: 6,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2013-01-01', created_at: '2013-01-01', updated_at: '2026-02-15',
  },
  {
    id: '78', slug: 'intercom', name: 'Intercom', tagline: 'AI-first customer service platform',
    description: 'Intercom is an AI-first customer service platform that helps businesses build better relationships with customers through personalized messaging and AI support.',
    logo_url: 'https://www.google.com/s2/favicons?domain=intercom.com&sz=128',
    website_url: 'https://intercom.com', category: 'Customer Support', pricing_model: 'Paid',
    tags: ['customer support', 'AI', 'messaging', 'CRM'], badges: ['top_rated', 'editors_pick'],
    upvote_count: 2340, review_count: 876, average_rating: 4.5, rank_score: 9100, weekly_rank_change: -3,
    is_featured: false, is_verified: false, is_pro: true,
    launched_at: '2011-01-01', created_at: '2011-01-01', updated_at: '2026-03-01',
  },
  {
    id: '79', slug: 'drift', name: 'Drift', tagline: 'Conversational marketing platform',
    description: 'Drift is a conversational marketing and sales platform that uses AI chatbots to engage website visitors, qualify leads, and book meetings automatically.',
    logo_url: 'https://www.google.com/s2/favicons?domain=drift.com&sz=128',
    website_url: 'https://drift.com', category: 'Customer Support', pricing_model: 'Paid',
    tags: ['chatbot', 'marketing', 'sales', 'AI'], badges: [],
    upvote_count: 1120, review_count: 345, average_rating: 4.3, rank_score: 8300, weekly_rank_change: 10,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2015-01-01', created_at: '2015-01-01', updated_at: '2026-01-15',
  },
  {
    id: '80', slug: 'ada', name: 'Ada', tagline: 'AI customer service automation',
    description: 'Ada is an AI-powered customer service automation platform that helps businesses resolve customer inquiries automatically at scale.',
    logo_url: 'https://www.google.com/s2/favicons?domain=ada.cx&sz=128',
    website_url: 'https://ada.cx', category: 'Customer Support', pricing_model: 'Paid',
    tags: ['customer service', 'AI', 'automation', 'enterprise'], badges: [],
    upvote_count: 670, review_count: 187, average_rating: 4.3, rank_score: 7800, weekly_rank_change: 16,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2016-01-01', created_at: '2016-01-01', updated_at: '2025-12-01',
  },
  {
    id: '81', slug: 'freshchat-ai', name: 'Freshchat AI', tagline: 'AI-powered customer messaging',
    description: 'Freshchat is an AI-powered customer messaging platform that helps businesses engage customers across channels with intelligent bots and live agents.',
    logo_url: 'https://www.google.com/s2/favicons?domain=freshworks.com&sz=128',
    website_url: 'https://freshworks.com/freshchat', category: 'Customer Support', pricing_model: 'Freemium',
    tags: ['customer support', 'AI', 'messaging', 'chatbot'], badges: ['best_value'],
    upvote_count: 540, review_count: 143, average_rating: 4.2, rank_score: 7600, weekly_rank_change: 4,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2016-01-01', created_at: '2016-01-01', updated_at: '2025-11-01',
  },

  // ── Research (5) ─────────────────────────────────────────────────────────
  {
    id: '82', slug: 'elicit', name: 'Elicit', tagline: 'AI research assistant for academics',
    description: 'Elicit is an AI research assistant that helps you find, summarize, and synthesize academic papers. It uses language models to automate literature reviews.',
    logo_url: 'https://www.google.com/s2/favicons?domain=elicit.com&sz=128',
    website_url: 'https://elicit.org', category: 'AI Analytics', pricing_model: 'Freemium',
    tags: ['research', 'academic', 'AI', 'papers'], badges: ['editors_pick'],
    upvote_count: 870, review_count: 234, average_rating: 4.5, rank_score: 8300, weekly_rank_change: 22,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2021-01-01', created_at: '2021-01-01', updated_at: '2026-02-01',
  },
  {
    id: '83', slug: 'consensus', name: 'Consensus', tagline: 'AI search engine for research papers',
    description: 'Consensus is an AI-powered search engine that finds answers in scientific research. Ask any question and get evidence-based answers from peer-reviewed papers.',
    logo_url: 'https://www.google.com/s2/favicons?domain=consensus.app&sz=128',
    website_url: 'https://consensus.app', category: 'AI Analytics', pricing_model: 'Freemium',
    tags: ['research', 'science', 'AI', 'papers'], badges: ['trending'],
    upvote_count: 760, review_count: 198, average_rating: 4.4, rank_score: 8100, weekly_rank_change: 1,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2022-01-01', created_at: '2022-01-01', updated_at: '2026-01-15',
  },
  {
    id: '84', slug: 'humata', name: 'Humata', tagline: 'Chat with your documents using AI',
    description: 'Humata is an AI product that lets you ask questions about your documents and get instant answers. Upload PDFs and get summaries, insights, and analysis.',
    logo_url: 'https://www.google.com/s2/favicons?domain=humata.ai&sz=128',
    website_url: 'https://humata.ai', category: 'AI Analytics', pricing_model: 'Freemium',
    tags: ['documents', 'PDF', 'AI', 'research'], badges: ['best_value'],
    upvote_count: 540, review_count: 143, average_rating: 4.3, rank_score: 7700, weekly_rank_change: 9,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2022-01-01', created_at: '2022-01-01', updated_at: '2025-12-01',
  },
  {
    id: '85', slug: 'scispace', name: 'SciSpace', tagline: 'AI product for scientific research',
    description: 'SciSpace is an AI-powered research tool that helps you discover, read, and understand scientific papers. Ask questions about any paper and get instant explanations.',
    logo_url: 'https://www.google.com/s2/favicons?domain=typeset.io&sz=128',
    website_url: 'https://typeset.io', category: 'AI Analytics', pricing_model: 'Freemium',
    tags: ['research', 'science', 'AI', 'papers'], badges: [],
    upvote_count: 430, review_count: 112, average_rating: 4.2, rank_score: 7400, weekly_rank_change: 14,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2020-01-01', created_at: '2020-01-01', updated_at: '2025-11-01',
  },
  {
    id: '86', slug: 'explainpaper', name: 'Explainpaper', tagline: 'AI explains complex research papers',
    description: 'Explainpaper is an AI product that helps you understand complex academic papers. Highlight confusing text and get a plain-English explanation instantly.',
    logo_url: 'https://www.google.com/s2/favicons?domain=explainpaper.com&sz=128',
    website_url: 'https://explainpaper.com', category: 'AI Analytics', pricing_model: 'Freemium',
    tags: ['research', 'papers', 'AI', 'education'], badges: [],
    upvote_count: 340, review_count: 87, average_rating: 4.1, rank_score: 7000, weekly_rank_change: -2,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2022-01-01', created_at: '2022-01-01', updated_at: '2025-10-01',
  },

  // ── No-Code (5) ──────────────────────────────────────────────────────────
  {
    id: '87', slug: 'bubble', name: 'Bubble', tagline: 'No-code web app builder',
    description: 'Bubble is a no-code platform that lets you build web applications without writing code. Create fully functional apps with a visual drag-and-drop editor.',
    logo_url: 'https://www.google.com/s2/favicons?domain=bubble.io&sz=128',
    website_url: 'https://bubble.io', category: 'Developer Tools', pricing_model: 'Freemium',
    tags: ['no-code', 'web app', 'builder', 'visual'], badges: ['top_rated', 'community_pick'],
    upvote_count: 2340, review_count: 876, average_rating: 4.5, rank_score: 9000, weekly_rank_change: 7,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2012-01-01', created_at: '2012-01-01', updated_at: '2026-03-01',
  },
  {
    id: '88', slug: 'glide', name: 'Glide', tagline: 'Build apps from Google Sheets',
    description: 'Glide is a no-code app builder that turns your Google Sheets and other data sources into beautiful mobile and web apps in minutes.',
    logo_url: 'https://www.google.com/s2/favicons?domain=glideapps.com&sz=128',
    website_url: 'https://glideapps.com', category: 'Developer Tools', pricing_model: 'Freemium',
    tags: ['no-code', 'Google Sheets', 'app builder', 'mobile'], badges: ['best_value'],
    upvote_count: 1120, review_count: 345, average_rating: 4.4, rank_score: 8400, weekly_rank_change: 19,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2018-01-01', created_at: '2018-01-01', updated_at: '2026-01-15',
  },
  {
    id: '89', slug: 'webflow', name: 'Webflow', tagline: 'No-code website builder for designers',
    description: 'Webflow is a no-code website builder that gives designers the power to build professional, custom websites without writing code.',
    logo_url: 'https://www.google.com/s2/favicons?domain=webflow.com&sz=128',
    website_url: 'https://webflow.com', category: 'Developer Tools', pricing_model: 'Freemium',
    tags: ['no-code', 'website builder', 'design', 'CMS'], badges: ['top_rated', 'editors_pick'],
    upvote_count: 3120, review_count: 1120, average_rating: 4.7, rank_score: 9400, weekly_rank_change: 3,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2013-01-01', created_at: '2013-01-01', updated_at: '2026-03-01',
  },
  {
    id: '90', slug: 'softr', name: 'Softr', tagline: 'Build web apps from Airtable',
    description: 'Softr is a no-code platform that lets you build web apps, client portals, and internal tools from Airtable or Google Sheets in minutes.',
    logo_url: 'https://www.google.com/s2/favicons?domain=softr.io&sz=128',
    website_url: 'https://softr.io', category: 'Developer Tools', pricing_model: 'Freemium',
    tags: ['no-code', 'Airtable', 'web app', 'portals'], badges: [],
    upvote_count: 760, review_count: 198, average_rating: 4.3, rank_score: 7900, weekly_rank_change: 11,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2019-01-01', created_at: '2019-01-01', updated_at: '2026-01-01',
  },
  {
    id: '91', slug: 'flutterflow', name: 'FlutterFlow', tagline: 'Visual app builder for Flutter',
    description: 'FlutterFlow is a low-code development platform that lets you build native mobile apps visually using Flutter. Deploy to iOS, Android, and web.',
    logo_url: 'https://www.google.com/s2/favicons?domain=flutterflow.io&sz=128',
    website_url: 'https://flutterflow.io', category: 'Developer Tools', pricing_model: 'Freemium',
    tags: ['no-code', 'Flutter', 'mobile', 'app builder'], badges: ['trending'],
    upvote_count: 1230, review_count: 398, average_rating: 4.4, rank_score: 8500, weekly_rank_change: -4,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2020-01-01', created_at: '2020-01-01', updated_at: '2026-02-01',
  },

  // ── Developer Tools (4) ──────────────────────────────────────────────────
  {
    id: '92', slug: 'vercel', name: 'Vercel', tagline: 'Deploy web apps instantly',
    description: 'Vercel is a cloud platform for frontend developers, providing the speed and reliability innovators need to create at the moment of inspiration.',
    logo_url: 'https://www.google.com/s2/favicons?domain=vercel.com&sz=128',
    website_url: 'https://vercel.com', category: 'Developer Tools', pricing_model: 'Freemium',
    tags: ['deployment', 'hosting', 'frontend', 'CI/CD'], badges: ['laudstack_pick', 'trending'],
    upvote_count: 3890, review_count: 1120, average_rating: 4.8, rank_score: 9700, weekly_rank_change: 13,
    is_featured: false, is_verified: true, is_pro: false,
    launched_at: '2015-12-01', created_at: '2015-12-01', updated_at: '2026-03-01',
  },
  {
    id: '93', slug: 'supabase', name: 'Supabase', tagline: 'The open source Firebase alternative',
    description: 'Supabase is an open source backend-as-a-service. Start your project with a Postgres database, authentication, instant APIs, edge functions, and storage.',
    logo_url: 'https://www.google.com/s2/favicons?domain=supabase.com&sz=128',
    website_url: 'https://supabase.com', category: 'Developer Tools', pricing_model: 'Freemium',
    tags: ['database', 'backend', 'open source', 'PostgreSQL'], badges: ['trending', 'new_launch'],
    upvote_count: 3240, review_count: 876, average_rating: 4.7, rank_score: 9450, weekly_rank_change: 5,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2020-01-01', created_at: '2020-01-01', updated_at: '2026-03-01',
  },
  {
    id: '94', slug: 'linear', name: 'Linear', tagline: 'The issue tracker for modern teams',
    description: 'Linear is the new standard for modern software development. Streamline issues, sprints, and product roadmaps.',
    logo_url: 'https://www.google.com/s2/favicons?domain=linear.app&sz=128',
    website_url: 'https://linear.app', category: 'Project Management', pricing_model: 'Freemium',
    tags: ['project management', 'issues', 'sprints', 'roadmap'], badges: ['laudstack_pick'],
    upvote_count: 1876, review_count: 654, average_rating: 4.8, rank_score: 9420, weekly_rank_change: 17,
    is_featured: false, is_verified: true, is_pro: true,
    launched_at: '2020-01-01', created_at: '2020-01-01', updated_at: '2026-03-01',
  },
  {
    id: '95', slug: 'cal-com', name: 'Cal.com', tagline: 'Open source scheduling infrastructure',
    description: 'Cal.com is the open source Calendly alternative. Schedule meetings, manage availability, and integrate with your existing tools — all with full data ownership.',
    logo_url: 'https://www.google.com/s2/favicons?domain=cal.com&sz=128',
    website_url: 'https://cal.com', category: 'AI Productivity', pricing_model: 'Open Source',
    tags: ['scheduling', 'calendar', 'open source', 'meetings'], badges: ['new_launch', 'trending'],
    upvote_count: 1450, review_count: 432, average_rating: 4.6, rank_score: 8600, weekly_rank_change: 2,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2021-09-01', created_at: '2021-09-01', updated_at: '2026-03-01',
  },

  // ── CRM / Sales (5) ──────────────────────────────────────────────────────
  {
    id: '96', slug: 'hubspot-ai', name: 'HubSpot AI', tagline: 'AI-powered CRM and marketing',
    description: 'HubSpot is an AI-powered CRM platform with tools for marketing, sales, service, and content management. ChatSpot AI assistant helps you work faster.',
    logo_url: 'https://www.google.com/s2/favicons?domain=hubspot.com&sz=128',
    website_url: 'https://hubspot.com', category: 'CRM', pricing_model: 'Freemium',
    tags: ['CRM', 'marketing', 'sales', 'AI'], badges: ['top_rated', 'community_pick'],
    upvote_count: 2890, review_count: 1120, average_rating: 4.5, rank_score: 9100, weekly_rank_change: 8,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2006-01-01', created_at: '2006-01-01', updated_at: '2026-03-01',
  },
  {
    id: '97', slug: 'apollo-io', name: 'Apollo.io', tagline: 'AI-powered sales intelligence',
    description: 'Apollo.io is an AI-powered sales intelligence and engagement platform with a database of 275M+ contacts. Find leads, automate outreach, and close deals faster.',
    logo_url: 'https://www.google.com/s2/favicons?domain=apollo.io&sz=128',
    website_url: 'https://apollo.io', category: 'Sales', pricing_model: 'Freemium',
    tags: ['sales', 'lead generation', 'AI', 'outreach'], badges: ['trending', 'editors_pick'],
    upvote_count: 1890, review_count: 654, average_rating: 4.5, rank_score: 8900, weekly_rank_change: 23,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2015-01-01', created_at: '2015-01-01', updated_at: '2026-03-01',
  },
  {
    id: '98', slug: 'clay', name: 'Clay', tagline: 'AI data enrichment for outbound sales',
    description: 'Clay is an AI-powered data enrichment and outbound sales tool that helps you build targeted prospect lists and personalize outreach at scale.',
    logo_url: 'https://www.google.com/s2/favicons?domain=clay.com&sz=128',
    website_url: 'https://clay.com', category: 'Sales', pricing_model: 'Paid',
    tags: ['sales', 'data enrichment', 'AI', 'outbound'], badges: ['new_launch', 'trending'],
    upvote_count: 1230, review_count: 398, average_rating: 4.6, rank_score: 8700, weekly_rank_change: -1,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2021-01-01', created_at: '2021-01-01', updated_at: '2026-03-01',
  },
  {
    id: '99', slug: 'gong', name: 'Gong', tagline: 'AI revenue intelligence platform',
    description: 'Gong is a revenue intelligence platform that uses AI to analyze customer interactions and provide insights to help sales teams close more deals.',
    logo_url: 'https://www.google.com/s2/favicons?domain=gong.io&sz=128',
    website_url: 'https://gong.io', category: 'Sales', pricing_model: 'Paid',
    tags: ['sales', 'revenue intelligence', 'AI', 'calls'], badges: ['top_rated'],
    upvote_count: 1560, review_count: 543, average_rating: 4.6, rank_score: 8900, weekly_rank_change: 6,
    is_featured: false, is_verified: false, is_pro: true,
    launched_at: '2015-01-01', created_at: '2015-01-01', updated_at: '2026-02-15',
  },
  {
    id: '100', slug: 'lavender', name: 'Lavender', tagline: 'AI email coach for sales reps',
    description: 'Lavender is an AI email coach that helps sales reps write better cold emails faster. It analyzes your emails in real-time and gives personalized suggestions.',
    logo_url: 'https://www.google.com/s2/favicons?domain=lavender.ai&sz=128',
    website_url: 'https://lavender.ai', category: 'Sales', pricing_model: 'Freemium',
    tags: ['sales', 'email', 'AI', 'cold outreach'], badges: ['best_value'],
    upvote_count: 870, review_count: 234, average_rating: 4.4, rank_score: 8200, weekly_rank_change: 15,
    is_featured: false, is_verified: false, is_pro: false,
    launched_at: '2020-01-01', created_at: '2020-01-01', updated_at: '2026-02-01',
  },
];

export const MOCK_LEADERBOARD: LeaderboardEntry[] = MOCK_TOOLS.map((tool, i) => ({
  rank: i + 1,
  tool,
  rank_change: [2, -1, 0, 3, 1, -2, 0, -1, 4, -3, 1, 0, 2, -1, 3, 0, -2, 1, 4, -1][i % 20] ?? 0,
  period: 'weekly',
}));

export const MOCK_REVIEWS: Review[] = [
  {
    id: 'r1', tool_id: '8', user_id: 'u1', rating: 5,
    title: 'Best AI writing tool I\'ve used',
    body: 'Writesonic has completely transformed how I create content. The quality is exceptional and it saves me hours every week.',
    pros: 'Fast, high quality output, great SEO features',
    cons: 'Can be a bit pricey for solo creators',
    use_case: 'Blog content and social media copy',
    is_verified_purchase: true, helpful_count: 42,
    created_at: '2026-02-15',
    user: { id: 'u1', name: 'Sarah Chen', avatar_url: undefined, role: 'Content Marketer', company: 'GrowthLabs' },
  },
  {
    id: 'r2', tool_id: '8', user_id: 'u2', rating: 4,
    title: 'Solid tool with room to grow',
    body: 'Overall very happy with Writesonic. The AI output is consistently good and the team ships updates regularly.',
    pros: 'Reliable, good templates, responsive support',
    cons: 'UI could be more intuitive',
    is_verified_purchase: true, helpful_count: 18,
    created_at: '2026-01-28',
    user: { id: 'u2', name: 'Marcus Rivera', role: 'Founder', company: 'Startup Studio' },
    founder_reply: {
      body: 'Thanks Marcus! We\'re actively working on a UI refresh — stay tuned for updates in Q2.',
      created_at: '2026-01-30',
    },
  },
  {
    id: 'r3', tool_id: '56', user_id: 'u3', rating: 5,
    title: 'Notion replaced every other tool in my stack',
    body: 'I moved my entire team onto Notion two years ago and we\'ve never looked back. Docs, wikis, project tracking — all in one place.',
    pros: 'Incredibly flexible, great templates, excellent collaboration',
    cons: 'Can be slow on large databases',
    use_case: 'Team knowledge base and project management',
    is_verified_purchase: true, helpful_count: 87,
    created_at: '2026-02-20',
    user: { id: 'u3', name: 'Priya Nair', role: 'Engineering Manager', company: 'Fintech Co.' },
  },
  {
    id: 'r4', tool_id: '17', user_id: 'u4', rating: 4,
    title: 'Midjourney is still the best for creative work',
    body: 'The v6 model is a massive leap forward. Photorealistic outputs, great prompt adherence. A must-have for any creative team.',
    pros: 'Best image quality, active community, fast iteration',
    cons: 'No web app, Discord-only workflow is clunky',
    use_case: 'Marketing visuals and concept art',
    is_verified_purchase: true, helpful_count: 63,
    created_at: '2026-02-10',
    user: { id: 'u4', name: 'James Okafor', role: 'Creative Director', company: 'Brand Studio' },
  },
  {
    id: 'r5', tool_id: '52', user_id: 'u5', rating: 5,
    title: 'Cursor is the future of coding',
    body: 'I\'ve tried every AI code editor and Cursor is in a league of its own. The tab completion is eerily accurate and the chat mode understands full codebases.',
    pros: 'Best-in-class autocomplete, codebase-aware chat, fast',
    cons: 'Subscription cost adds up for teams',
    use_case: 'Full-stack development and code reviews',
    is_verified_purchase: true, helpful_count: 112,
    created_at: '2026-03-01',
    user: { id: 'u5', name: 'Alex Kim', role: 'Senior Engineer', company: 'Series B Startup' },
  },
  {
    id: 'r6', tool_id: '94', user_id: 'u6', rating: 5,
    title: 'Linear made our sprints actually enjoyable',
    body: 'After years of Jira, Linear feels like a breath of fresh air. The keyboard shortcuts alone save me 30 minutes a day.',
    pros: 'Lightning fast, beautiful UI, great keyboard shortcuts',
    cons: 'Limited reporting compared to Jira',
    use_case: 'Sprint planning and bug tracking',
    is_verified_purchase: true, helpful_count: 55,
    created_at: '2026-02-05',
    user: { id: 'u6', name: 'Sofia Andersen', role: 'Product Manager', company: 'SaaS Platform' },
  },
  {
    id: 'r7', tool_id: '3', user_id: 'u7', rating: 4,
    title: 'Perplexity is my new Google',
    body: 'I use Perplexity for almost every research query now. The cited sources make it trustworthy in a way that ChatGPT isn\'t.',
    pros: 'Real-time web search, cited sources, clean UI',
    cons: 'Pro plan required for GPT-4 model access',
    use_case: 'Research and fact-checking',
    is_verified_purchase: true, helpful_count: 34,
    created_at: '2026-01-18',
    user: { id: 'u7', name: 'Tom Whitfield', role: 'Analyst', company: 'Research Firm' },
  },
  {
    id: 'r8', tool_id: '37', user_id: 'u8', rating: 5,
    title: 'ElevenLabs voices are indistinguishable from humans',
    body: 'I use ElevenLabs for all my podcast intros and YouTube narration. The voice quality is absolutely stunning — listeners can\'t tell it\'s AI.',
    pros: 'Hyper-realistic voices, huge library, great API',
    cons: 'Premium voices require higher tier plan',
    use_case: 'Podcast production and YouTube content',
    is_verified_purchase: true, helpful_count: 78,
    created_at: '2026-02-25',
    user: { id: 'u8', name: 'Lena Müller', role: 'Content Creator', company: 'Independent' },
  },
  {
    id: 'r9', tool_id: '69', user_id: 'u9', rating: 5,
    title: 'Figma is the gold standard for design collaboration',
    body: 'Our entire design team lives in Figma. The real-time collaboration, component libraries, and developer handoff are unmatched.',
    pros: 'Real-time collaboration, powerful components, great plugins',
    cons: 'Can be slow with very large files',
    use_case: 'Product design and developer handoff',
    is_verified_purchase: true, helpful_count: 134,
    created_at: '2026-03-02',
    user: { id: 'u9', name: 'Yuki Tanaka', role: 'Lead Designer', company: 'Product Studio' },
  },
  {
    id: 'r10', tool_id: '1', user_id: 'u10', rating: 4,
    title: 'ChatGPT is still the most versatile AI product',
    body: 'Despite all the competition, ChatGPT remains my daily driver. The breadth of tasks it handles — coding, writing, analysis — is unmatched.',
    pros: 'Versatile, fast, great plugins ecosystem',
    cons: 'Hallucinations still happen, needs fact-checking',
    use_case: 'Daily work assistant and research',
    is_verified_purchase: true, helpful_count: 91,
    created_at: '2026-03-05',
    user: { id: 'u10', name: 'David Park', role: 'Startup Founder', company: 'TechVentures' },
  },
];

// ── Category catalog ────────────────────────────────────────────────────
export const CATEGORIES: { name: string; icon: string; count: number; description: string }[] = [
  { name: 'All', icon: '🌐', count: MOCK_TOOLS.length, description: 'All tools on LaudStack' },
  { name: 'AI Productivity', icon: '⚡', count: MOCK_TOOLS.filter(t => t.category === 'AI Productivity').length, description: 'AI-powered productivity and automation tools' },
  { name: 'AI Writing', icon: '✍️', count: MOCK_TOOLS.filter(t => t.category === 'AI Writing').length, description: 'AI writing assistants and content generators' },
  { name: 'AI Image', icon: '🎨', count: MOCK_TOOLS.filter(t => t.category === 'AI Image').length, description: 'AI image generation and editing tools' },
  { name: 'AI Video', icon: '🎬', count: MOCK_TOOLS.filter(t => t.category === 'AI Video').length, description: 'AI video creation and editing platforms' },
  { name: 'AI Audio', icon: '🎙️', count: MOCK_TOOLS.filter(t => t.category === 'AI Audio').length, description: 'AI voice generation and audio tools' },
  { name: 'AI Code', icon: '💻', count: MOCK_TOOLS.filter(t => t.category === 'AI Code').length, description: 'AI coding assistants and developer tools' },
  { name: 'AI Analytics', icon: '📊', count: MOCK_TOOLS.filter(t => t.category === 'AI Analytics').length, description: 'AI-powered analytics and research tools' },
  { name: 'Design', icon: '🖌️', count: MOCK_TOOLS.filter(t => t.category === 'Design').length, description: 'Design tools for creators and teams' },
  { name: 'Marketing', icon: '📣', count: MOCK_TOOLS.filter(t => t.category === 'Marketing').length, description: 'Marketing and SEO platforms' },
  { name: 'Developer Tools', icon: '🔧', count: MOCK_TOOLS.filter(t => t.category === 'Developer Tools').length, description: 'Tools for developers and engineers' },
  { name: 'Project Management', icon: '📋', count: MOCK_TOOLS.filter(t => t.category === 'Project Management').length, description: 'Project and task management platforms' },
  { name: 'Customer Support', icon: '💬', count: MOCK_TOOLS.filter(t => t.category === 'Customer Support').length, description: 'Customer service and support tools' },
  { name: 'CRM', icon: '🤝', count: MOCK_TOOLS.filter(t => t.category === 'CRM').length, description: 'Customer relationship management platforms' },
  { name: 'Sales', icon: '💰', count: MOCK_TOOLS.filter(t => t.category === 'Sales').length, description: 'Sales intelligence and outreach products' },
];
